
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PUBDB"."AES_CARTEIRA_ANALISE_V" ("FILIAL", "TIPO_PEDIDO", "COD_CLIENTE", "TRANSPORTADORA", "TRANSPORTADORA_NOVA", "REDESPACHO", "CIDADE_REDESPACHO", "CIDADE_CLIENTE", "COD_VENDEDOR", "PC_CLIENTE", "COD_PAGAMENTO", "VALOR_PEDIDO_TOTAL", "INSTRUCAO_ENTREGA", "STATUS", "DATA_FINAL", "DATA_PEDIDO", "DATA_SOLICITADA", "DATA_PCP", "MSG_IMPRIMIR", "ANEXO_FAT", "TIPO_FRETE", "PEDIDO", "BLOQUEIO", "DSC_COND_PAG", "COND_QTD_PARCELAS", "LINHA", "PROX_STATUS", "PROX_STATUS2", "ULTIMO_STATUS", "CODIGO", "QTD_PRINC", "UM", "QTD_SEC", "UM2", "PRECO_UNIT", "PRECO_BT", "COD_MSG_IMPRIMIR", "QTD_TRANSITO", "MONITORAMENTO") AS 
  SELECT DISTINCT

    CARTEIRA_ANALISE.FILIAL,
    CARTEIRA_ANALISE.TIPO_PEDIDO,
    TO_CHAR(CARTEIRA_ANALISE.COD_CLIENTE) AS COD_CLIENTE,
    CARTEIRA_ANALISE.COD_TRANSP AS TRANSPORTADORA,
    
    CASE 
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ALUMINIO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) AMERICANA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) AMPARO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ARUJA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) CAMPINAS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) BARUERI%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) BIRITIBA MIRIM%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) CAIEIRAS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) CAJAMAR%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) CARAPICUIBA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) COTIA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) CUBATAO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) DIADEMA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) EMBU DAS ARTES%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) EMBUGUACU%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) FERRAZ DE VASCONCELOS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) FRANCISCO MORATO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) FRANCO DA ROCHA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) GUARAREMA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) GUARUJA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) GUARULHOS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) HORTOLANDIA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) IBIUNA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) INDAIATUBA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ITAPECERICA DA SERRA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ITAPEVI%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ITAQUAQUECETUBA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ITATIBA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ITU%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) ITUPEVA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) JACAREI%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) JAGUARIUNA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) JANDIRA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) JUNDIAI%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) JUQUITIBA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) LOUVEIRA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) MAIRINQUE%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) MAIRIPORA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) MAUA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) MOGI DAS CRUZES%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) NOVA ODESSA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) OSASCO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) PAULINIA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) PIRAPORA DO BOM JESUS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) POA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) PRAIA GRANDE%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) RIBEIRAO PIRES%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) RIO GRANDE DA SERRA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SALESOPOLIS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SALTO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SANTA ISABEL%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SANTANA DE PARNAIBA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SANTO ANDRE%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SANTOS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SAO BERNARDO DO CAMPO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SAO CAETANO DO SUL%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SAO JOSE DOS CAMPOS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SAO LOURENCO DA SERRA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SAO PAULO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SAO ROQUE%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SOROCABA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) SUZANO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) TABOAO DA SERRA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) VALINHOS%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) VARGEM GRANDE PAULISTA%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP) VINHEDO%' THEN '870916'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(AC)%' THEN '1028394'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(AL)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(AM)%' THEN '1028394'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(AP)%' THEN '1028394'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(BA)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(CE)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(DF)%' THEN '1000672'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(ES)%' THEN '1072048'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(GO)%' THEN '1000672'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(MA)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(MG)%' THEN '1445996'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(MS)%' THEN '1000672'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(MT)%' THEN '1000672'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(PA)%' THEN '1028394'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(PB)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(PE)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(PI)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(PR)%' THEN '918555'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(RJ)%' THEN '1072048'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(RN)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(RO)%' THEN '1000672'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(RR)%' THEN '1028394'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(RS)%' THEN '1000029'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SC)%' THEN '918555'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SE)%' THEN '1037557'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(SP)%' THEN '709790'
    WHEN CARTEIRA_ANALISE.TIPO_FRETE LIKE 'A%' AND CARTEIRA_ANALISE.CIDADE_PARA_TRANSPORTADORA LIKE '%(TO)%' THEN '1028394' 
    END   AS TRANSPORTADORA_NOVA, 
 
    CARTEIRA_ANALISE.COD_REDESPACHO AS REDESPACHO,
    CARTEIRA_ANALISE.CIDADE_REDESPACHO,
    CARTEIRA_ANALISE.CIDADE_CLIENTE,
    CARTEIRA_ANALISE.COD_VENDEDOR,
    CARTEIRA_ANALISE.PC_CLIENTE,
    CARTEIRA_ANALISE.COD_PAGAMENTO,
    CARTEIRA_ANALISE.VALOR_PEDIDO_TOTAL,
    CARTEIRA_ANALISE.INSTRUCAO_ENTREGA,
    CARTEIRA_ANALISE.STATUS,  
    /* CALCULA PARA DEFINIR A DATA FINAL*/
    CARTEIRA_ANALISE.DATA_FINAL,
    CARTEIRA_ANALISE.DATA_PEDIDO,
    CARTEIRA_ANALISE.DATA_SOLICITADA,
    CARTEIRA_ANALISE.DATA_PCP,
    CARTEIRA_ANALISE.MSG_IMPRIMIR,
    CAST(CARTEIRA_ANALISE.ANEXO AS CHAR(350)) AS ANEXO_FAT ,
    CARTEIRA_ANALISE.TIPO_FRETE,
    CARTEIRA_ANALISE.PEDIDO,
    CARTEIRA_ANALISE.BLOQUEIO,
    /* DADOS DA CONDIÇÃO DE PAGAMENTO */
    CARTEIRA_ANALISE.DSC_COND_PAG,
    CARTEIRA_ANALISE.COND_QTD_PARCELAS,
    TO_CHAR(CARTEIRA_ANALISE.LINHA) AS LINHA,
    /* DEFINE O STATUS DO PEDIDO */
    CARTEIRA_ANALISE.PROX_STATUS,
    TO_CHAR(CARTEIRA_ANALISE.PROX_STATUS) AS PROX_STATUS2,
    CARTEIRA_ANALISE.ULTIMO_STATUS,
    CARTEIRA_ANALISE.CODIGO,
    CARTEIRA_ANALISE.QTD_PRINC,
    CARTEIRA_ANALISE.UM,
    CARTEIRA_ANALISE.QTD_SEC,
    CARTEIRA_ANALISE.UM2,
    CARTEIRA_ANALISE.PRECO_UNIT,
    CARTEIRA_ANALISE.PRECO_BT,
    MSG AS COD_MSG_IMPRIMIR,
    COALESCE(CARTEIRA_ANALISE.QTD_ABERTA,0) AS QTD_TRANSITO,
        /*CALCULO MONITORAMENTO*/
    CASE WHEN CARTEIRA_ANALISE.BLOQUEIO = 'A2' THEN '1.EM ANALISE'
         WHEN CARTEIRA_ANALISE.BLOQUEIO = 'C1' THEN '2. BLQ CREDITO'
         WHEN SUBSTR(CARTEIRA_ANALISE.DATA_SOLICITADA,1,10) < SUBSTR(CARTEIRA_ANALISE.DATA_FINAL,1,10) AND SUBSTR(CARTEIRA_ANALISE.DATA_PCP,1,10) < SUBSTR(CARTEIRA_ANALISE.DATA_FINAL,1,10) THEN '3.JA ATRASOU'
         WHEN SUBSTR(CARTEIRA_ANALISE.DATA_FINAL,1,10) <= SUBSTR(SYSDATE,1,10) THEN '4.DEVERIA FATURAR HOJE'
         WHEN SUBSTR(CARTEIRA_ANALISE.DATA_FINAL,1,10) <= SUBSTR((SYSDATE + 4),1,10) THEN '5.TA CHEGANDO A DATA'
         ELSE '6.DENTRO DO PRAZO' END AS MONITORAMENTO
FROM (


SELECT
    /* DADOS DO CABEÇALHO DO PEDIDO*/
    TRIM(CABECALHO_PEDIDO.SHMCU) AS FILIAL,
    CABECALHO_PEDIDO.SHDCTO AS TIPO_PEDIDO,
    CABECALHO_PEDIDO.SHAN8 AS COD_CLIENTE,
    CABECALHO_PEDIDO.SHCARS || ' - ' ||NT.ABALPH AS COD_TRANSP,
    END_C.CIDADE AS CIDADE_CLIENTE,
    END_R.CIDADE AS CIDADE_REDESPACHO,
    COALESCE(END_R.CIDADE,END_C.CIDADE) AS CIDADE_PARA_TRANSPORTADORA,
    CABECALHO_PEDIDO.SHPRAN8 || ' - ' ||NR.ABALPH AS COD_REDESPACHO,
    CABECALHO_PEDIDO.SHORBY AS COD_VENDEDOR,
    CABECALHO_PEDIDO.SHVR01 AS PC_CLIENTE,
    CABECALHO_PEDIDO.SHPTC AS COD_PAGAMENTO,
    CAST((CABECALHO_PEDIDO.SHOTOT / 100) AS DECIMAL(10, 2)) AS VALOR_PEDIDO_TOTAL,
    CABECALHO_PEDIDO.SHDEL1 || ' - ' || CABECALHO_PEDIDO.SHDEL2  AS INSTRUCAO_ENTREGA,
  TRIM(INF.AIINMG) AS MSG,
  CASE 

    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) < 621 AND NVL(TRIM(CABECALHO_PEDIDO.SHHOLD),'-') = 'A2' THEN '1.ANALISE CRITICA'
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) < 621 AND NVL(TRIM(CABECALHO_PEDIDO.SHHOLD),'-') = 'C1' THEN '2.BLOQUEIO DE CREDITO' 
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) = 540 AND TO_CHAR(DETALHE_PEDIDO.SDLTTR) = 914 THEN '0.SOBRA DE PEDIDO'  

    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) = 540 AND TO_CHAR(DETALHE_PEDIDO.SDLTTR) = 520 THEN '4.CARTEIRA'
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) = 541 AND TO_CHAR(DETALHE_PEDIDO.SDLTTR) = 540 THEN '5.LISTA DE FATURAMENTO'
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) = 541 AND TO_CHAR(DETALHE_PEDIDO.SDLTTR) = 914 THEN '3.SALDO DE FATURAMENTO' 
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) = 595 AND TO_CHAR(DETALHE_PEDIDO.SDLTTR) = 598 THEN '6.EM SEPARAÇÃO'
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) = 617 AND TO_CHAR(DETALHE_PEDIDO.SDLTTR) = 600 THEN '7.GERAÇÃO DA NOTA'
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) = 999 AND TO_CHAR(DETALHE_PEDIDO.SDLTTR) = 620 THEN '8.FATURADO'
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) >= 595 AND TO_CHAR(DETALHE_PEDIDO.SDNXTR) <= 600 THEN '7.GERAÇÃO DA NOTA'
    WHEN TO_CHAR(DETALHE_PEDIDO.SDNXTR) >= 541 AND TO_CHAR(DETALHE_PEDIDO.SDNXTR) <595  THEN '6.EM SEPARAÇÃO'

    ELSE '4.CARTEIRA' END AS STATUS,
    /* CALCULA PARA DEFINIR A DATA FINAL*/
    CASE 
        WHEN TO_DATE((DETALHE_PEDIDO.SDDRQJ + 1900000), 'YYYYDDD') >=  TO_DATE((DETALHE_PEDIDO.SDRSDJ + 1900000), 'YYYYDDD')AND TO_DATE((DETALHE_PEDIDO.SDDRQJ + 1900000), 'YYYYDDD') >= SYSDATE THEN TO_DATE((DETALHE_PEDIDO.SDDRQJ + 1900000), 'YYYYDDD') 
        WHEN TO_DATE((DETALHE_PEDIDO.SDRSDJ + 1900000), 'YYYYDDD')  >= TO_DATE((DETALHE_PEDIDO.SDDRQJ + 1900000), 'YYYYDDD') AND TO_DATE((DETALHE_PEDIDO.SDRSDJ + 1900000), 'YYYYDDD') >= SYSDATE THEN  TO_DATE((DETALHE_PEDIDO.SDRSDJ + 1900000), 'YYYYDDD')
     ELSE CURRENT_DATE END AS DATA_FINAL,

    TO_DATE((DETALHE_PEDIDO.SDTRDJ + 1900000), 'YYYYDDD') AS DATA_PEDIDO,
    TO_DATE((DETALHE_PEDIDO.SDDRQJ + 1900000), 'YYYYDDD') AS DATA_SOLICITADA,
    TO_DATE((DETALHE_PEDIDO.SDRSDJ + 1900000), 'YYYYDDD') AS DATA_PCP,
    CABECALHO_PEDIDO.SHINMG AS MSG_IMPRIMIR,
    ANEXO.ANEXO,

    CASE WHEN CABECALHO_PEDIDO.SHFRTH = 'A' THEN CABECALHO_PEDIDO.SHFRTH ||' - '|| 'CIF'
         WHEN CABECALHO_PEDIDO.SHFRTH = 'B' THEN CABECALHO_PEDIDO.SHFRTH ||' - '|| 'FOB'
         WHEN CABECALHO_PEDIDO.SHFRTH = 'D' THEN CABECALHO_PEDIDO.SHFRTH ||' - '|| 'FOB RETIRA'
         WHEN CABECALHO_PEDIDO.SHFRTH = 'E' THEN CABECALHO_PEDIDO.SHFRTH ||' - '|| 'RETIRA'
    END AS TIPO_FRETE,
    TO_CHAR(CABECALHO_PEDIDO.SHDOCO) AS PEDIDO,
    CABECALHO_PEDIDO.SHHOLD AS BLOQUEIO,
    /* DADOS DA CONDIÇÃO DE PAGAMENTO */
    COND_PAG.PNPTD AS DSC_COND_PAG,
    COND_PAG.PNNSP AS COND_QTD_PARCELAS,

    /*DADOS DETLAHE DO PEDIDO*/
    (DETALHE_PEDIDO.SDLNID / 1000) AS LINHA,
    /* DEFINE O STATUS DO PEDIDO */

    DETALHE_PEDIDO.SDNXTR AS PROX_STATUS,
    DETALHE_PEDIDO.SDLTTR AS ULTIMO_STATUS,
    DETALHE_PEDIDO.SDLITM AS CODIGO,
    (DETALHE_PEDIDO.SDUORG / 10000) AS QTD_PRINC,
    DETALHE_PEDIDO.SDUOM AS UM,
    (DETALHE_PEDIDO.SDPQOR / 10000) AS QTD_SEC,
    DETALHE_PEDIDO.SDUOM1 AS UM2,
    CAST((DETALHE_PEDIDO.SDUPRC / 10000) AS DECIMAL(10, 2)) AS PRECO_UNIT,
    CAST((DETALHE_PEDIDO.SDAEXP / 100) AS DECIMAL(10, 2)) AS PRECO_BT,
    ST.QTD_ABERTA
FROM
    PRODDTA.F4201 CABECALHO_PEDIDO
    /* JOIN PARA PEGAR DETALHES DO PEDIDO*/
    LEFT JOIN PRODDTA.F4211 DETALHE_PEDIDO ON TRIM(CABECALHO_PEDIDO.SHDOCO) = TRIM(DETALHE_PEDIDO.SDDOCO) AND TRIM(CABECALHO_PEDIDO.SHMCU) = TRIM(DETALHE_PEDIDO.SDMCU) AND TRIM(CABECALHO_PEDIDO.SHDCTO) = TRIM(DETALHE_PEDIDO.SDDCTO)
    AND CABECALHO_PEDIDO.SHDCTO = DETALHE_PEDIDO.SDDCTO
    AND TRIM(CABECALHO_PEDIDO.SHMCU) = TRIM(DETALHE_PEDIDO.SDMCU)
    AND DETALHE_PEDIDO.SDPQOR > 0
    AND DETALHE_PEDIDO.SDNXTR >= 540
    AND DETALHE_PEDIDO.SDNXTR <= 620

     /*JOIN PARA PEGAR DETALHES DA CONDIÇÃO DE PAGAMENTO*/
    LEFT JOIN PRODDTA.F0014 COND_PAG ON TRIM(CABECALHO_PEDIDO.SHPTC) = TRIM(COND_PAG.PNPTC)


     /*JOIN PARA PEGAR DETALHES DO MENSAGEM DO CLIENTE*/
    LEFT JOIN ( 
        select ROW_NUMBER() OVER(PARTITION BY AIAN8 ORDER BY  AIINMG desc ) AS RN,
        AIINMG, 
        AIAN8
        from PRODDTA.F03012
    ) INF ON TO_CHAR(CABECALHO_PEDIDO.SHAN8) = TRIM(INF.AIAN8) AND INF.RN=1

    /* PEGA INFORMAÇÃO DE FATURAMENTO */
    LEFT JOIN PUBDB.ANEXO_40_PM ANEXO ON TRIM(INF.AIINMG) = TRIM(ANEXO.COD)

/* PEGAR NOME DA TRANSPORTADORA */
LEFT JOIN PRODDTA.F0101 NT ON TRIM(CABECALHO_PEDIDO.SHCARS) = TRIM(NT.ABAN8) AND TRIM(NT.ABMCU) IN ('510000','110000')

/* PEGAR NOME DO REDESPACHO*/
LEFT JOIN PRODDTA.F0101 NR ON TRIM(CABECALHO_PEDIDO.SHPRAN8) = TRIM(NR.ABAN8) AND TRIM(NR.ABMCU) IN ('510000','110000')

/*PEGAR CIDADE DA REDESPACHO*/
LEFT JOIN (SELECT ALAN8 AS COD_TRANSP, '('||TRIM(ALADDS)||') '||ALCTY1 AS CIDADE FROM PRODDTA.F0116) END_R ON TRIM(CABECALHO_PEDIDO.SHPRAN8) = TRIM(END_R.COD_TRANSP)

/*PEGAR CIDADE DA CLIENTE*/
LEFT JOIN (SELECT ALAN8 AS COD_TRANSP, '('||TRIM(ALADDS)||') '||ALCTY1 AS CIDADE FROM PRODDTA.F0116) END_C ON TRIM(CABECALHO_PEDIDO.SHAN8) = TRIM(END_C.COD_TRANSP)

/* QUANTIDADE EM TRANSITO ST/OT AES > LGN */
LEFT JOIN (SELECT OT.PDLITM AS CODIGO, SUM(OT.PDSQOR/10000) AS QTD_ABERTA FROM PRODDTA.F4311 OT
WHERE OT.PDKCOO = '51000' AND TRIM(OT.PDMCU) = '511001' AND OT.PDDCTO = 'OT' AND OT.PDUOPN >= 1 
GROUP BY OT.PDLITM) ST ON TRIM(DETALHE_PEDIDO.SDLITM) = TRIM(ST.CODIGO)

    /* FILTROS DETALHES DO CABECALHO PEDIDO */
WHERE
    TRIM(CABECALHO_PEDIDO.SHMCU) = TRIM(DETALHE_PEDIDO.SDMCU)
    AND TRIM(CABECALHO_PEDIDO.SHMCU) IN ('511000', '511001')
    AND CABECALHO_PEDIDO.SHDCTO IN (
        'VO',
        'SX',
        'VA',
        'V7',
        'VH',
        'VQ',
        'V0',
      'VZ',
      'SA',
'S3',
'SF'
    )

    AND CABECALHO_PEDIDO.SHDCTO = DETALHE_PEDIDO.SDDCTO
    AND DETALHE_PEDIDO.SDPQOR > 0
    AND DETALHE_PEDIDO.SDNXTR >= 540
    AND DETALHE_PEDIDO.SDNXTR <= 620

 )CARTEIRA_ANALISE;