  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PUBDB"."CENTRO_CUSTO_EPM" ("MEMBRO", "MEMBRO_PAI", "DESCRICAO") AS 
  select 
'CC'||TRIM(MCMCU) MEMBRO,
'All Centro de Custo' MEMBRO_PAI,
TRIM(MCMCU) ||' - '||TRIM(MCDL01) DESCRICAO
from proddta.f0006
WHERE MCSTYL in ('CC','WC');
