CREATE VIEW PUBDB.JDE_SALES_CHILE_V AS
/*Tabela Virtual para conversosr de valores*/
WITH CONVERSOR AS (
    SELECT
    CXCRR*USD_BRL CONVERSOR,
    to_char(to_date((CXEFT + 1900000), 'YYYYDDD'), 'MM/YYYY') MES_ANO
    FROM proddta.F0015
    LEFT JOIN (
    SELECT AVG(CXCRR) USD_BRL,
    to_char(ADD_MONTHS(to_date((CXEFT + 1900000), 'YYYYDDD'),1), 'MM/YYYY') MES_ANO_BRL
    FROM proddta.F0015 WHERE CXCRCD='USD' AND CXCRDC='BRL'
    GROUP BY to_char(ADD_MONTHS(to_date((CXEFT + 1900000), 'YYYYDDD'),1), 'MM/YYYY')
    ) ON to_char(to_date((CXEFT + 1900000), 'YYYYDDD'), 'MM/YYYY')=MES_ANO_BRL
    WHERE CXCRCD='CLP' AND CXCRDC='USD'
    AND to_char(to_date((CXEFT + 1900000), 'YYYYDDD'), 'DD')='01'
)

SELECT distinct

RTH76LENU NOTA
, SDAN8 COD_GERAL_1
, CASE
WHEN CG.ABALKY IS NULL OR CG.ABALKY LIKE ' %' THEN trim(CG.ABALPH)
ELSE trim(CG.ABALPH) END CLIENTE
, trim(SDLITM) CODIGO
, TRIM(SDDSC1)||' '||TRIM(SDDSC2) DESCRICAO

, SDUOM1 UNIDADE
, (SDUORG/10000) QUANTIDADE
, sdaexp/(SDUORG/10000) VALOR_UNITARIO
, (sdaexp) TOTAL
,ROUND((sdaexp/(SDUORG/10000))*CONVERSOR ,4)VALOR_UNITARIO_BRL
, ROUND(sdaexp*CONVERSOR,2) TOTAL_BRL


, CASE RTH76IDPT WHEN 0 THEN ' ' ELSE TO_CHAR(TO_DATE((RTH76IDPT+1900000), 'YYYYDDD'), 'DD/MM/YYYY') END EMISSAO
,RTH76IDPT RTH76IDPT
, sdmcu FILIAL
, CP.PNPTD VENCIMENTO
, trim(TRANSP.ALCTY1) as CIDADE_TRANSP

, (CASE
WHEN
RE.ABAN8 = SH.SHORBY or SH.SHORBY!=' '
THEN
trim(to_char(SH.SHORBY)) ||' - '|| trim(to_char(RE.ABALKY))
ELSE
trim(to_char(CVEN.SHSLSM)) ||' - '|| trim(to_char(CRE.ABALKY))
END) AS REPRESENTATE

, (CO.ALFVTR/10000) COMISSAO
, ((SDUORG/10000)*(SDUPRC/10000)) * (CO.ALFVTR/1000000) as VALOR_COMISSAO
,trim(VD.SDMCU) as FILIAL_PEDIDO
,(VD.SDDOCO || ' / ' || VD.SDDCTO ||(Case
When VD.SDCORD !=0
THEN
' / ' || TO_CHAR(VD.SDCORD)
ELSE
''
END)) PEDIDO
,VD.SDDOCO PEDIDO2
, SDAN8 COD_GERAL

, 'OCQ CHILE' COMPANHIA
, VD.SDDCTO TIPO_DOC
,(SDAEXP) * 0.19 IMPOSTO

, trim(AL.ALCTY1) as CIDADE
, AL.ALADDS as ESTADO

, CN.DRDL01 as PAIS
, VD.SDCRR as TAXA_DOLAR
, (VD.SDFUP)/10000 as VALOR_UNITARIO_DOLAR
,(SDUORG/10000) * ((VD.SDFUP)/10000 ) TOTAL_DOLAR
, ((VD.SDUORG/10000)*(VD.SDFUP/10000)) as VALOR_TOTAL_DOLAR

, SDLOTN as LOTE
, trim(SH.SHFRTH) AS FRETE
, NVL2(trim(SDDSC2),trim(SDDSC2),'GRANEL') as EMBALAGEM
, TRIM(DF.DRDL01)||'('||trim(DF.DRKY)||')' as CLASSE_MERCADORIA
, TRIM(SB.DRDL01)||'('||trim(SB.DRKY)||')' as SUB_CLASSE
, NVL2(SB.DRDL01,TRIM(SB.DRDL01)||'('||trim(SB.DRKY)||')' ,' ') as SUBCLASSE_MERCADORIA

,(Case
When
trim(to_char(SH.SHDEL1)) like 'EXP%'
THEN
trim(to_char(SH.SHDEL1))
ELSE
''
END) AS REF_EXP
,SDLNID
,SDCRCD MOEDA
,CASE WHEN NVL(VD.sdTRDJ,0)='0' THEN '' ELSE TO_CHAR(TO_DATE((VD.sdTRDJ+1900000), 'YYYYDDD'), 'DD/MM/YYYY') END CRIACAO
,decode(trim(VD.SDUPC1),'S','Sem','Com') as Rotulo
,TRIm(RTTORG) USUARIO


FROM
proddta.f4211 VD
inner JOIN PRODDTA.F76H211 ON SLKCOO=SDKCOO AND SLDCTO=SDDCTO AND SLDOCO=SDDOCO AND SLLNID=SDLNID AND SLKCO=SDKCO
LEFT JOIN proddta.F76H3B10 ON RTKCO=SLKCO AND SLDCT=RTDCT AND RTDOC=SLDOC
inner join PRODDTA.F0101 CG ON SDAN8 = CG.ABAN8


left outer join PRODDTA.F0116 AL on CG.ABAN8=AL.ALAN8

inner join PRODDTA.F4101 IM ON SDITM = IM.IMITM

left outer join PRODDTA.F0014 CP ON VD.SDPTC = CP.PNPTC
left outer join PRODDTA.F4074 CO ON CO.ALDOCO= VD.SDDOCO AND CO.ALDCTO= VD.SDDCTO AND CO.ALKCOO = VD.SDCO AND CO.ALLNID= VD.SDLNID AND CO.ALASN= 'CALCCOM ' AND CO.ALAST = 'COMIS '
left outer join PRODCTL.F0005 CN ON TRIM(CN.DRSY) = '00' AND TRIM(CN.DRRT) = 'CN' AND TRIM(CN.DRKY) = TRIM(AL.ALCTR)
left outer join PRODDTA.F4201 SH ON VD.SDDOCO = SH.SHDOCO AND VD.SDDCTO = SH.SHDCTO AND VD.SDMCU = SH.SHMCU
left outer join PRODDTA.F0116 TRANSP on SHCARS=TRANSP.ALAN8
left outer join PRODDTA.F0101 RE ON trim(RE.ABAN8) = trim(SH.SHORBY)
left outer join PRODDTA.F42150 CVEN ON VD.SDDOCO = CVEN.SHDOCO AND VD.SDDCTO = CVEN.SHDCTO AND VD.SDKCOO = CVEN.SHKCOO AND CVEN.SHSLSM!='1303901'
left outer join PRODDTA.F0101 CRE ON trim(CRE.ABAN8) = trim(CVEN.SHSLSM)
left outer join PRODCTL.F0005 DF ON trim(DF.DRKY) = TRIM(IM.IMSRP1) and DF.DRSY = '41' AND DF.DRRT = 'P1'
left outer join PRODCTL.F0005 SB ON trim(SB.DRKY) = TRIM(IM.IMSRP2) and SB.DRSY = '41' AND SB.DRRT = 'P2' -- inserido por carol 23/11/2015
LEFT JOIN CONVERSOR ON RTH76IDPT>'0' AND TO_CHAR(TO_DATE((RTH76IDPT+1900000), 'YYYYDDD'), 'MM/YYYY') =MES_ANO


WHERE
    VD.SDNXTR >='600'
    AND SDCO='71000'
    AND VD.SDLTTR not in ('980', '996')
    AND SDDCTO IN ('VO', 'SG', 'SO', 'V7', 'VI', 'VH', 'VQ', 'SX', 'VA', 'V5', 'VG', 'VZ', 'V8','VY','VN','VU')
    AND VD.SDDCTO NOT LIKE 'D%'
    /*referente a 01/2023*/
    AND RTH76IDPT >= 123001
order by RTH76IDPT