SELECT
TIPO,
FILIAL,
TRIM(MCDL01) AS FILIAL2,
CASE 
WHEN SUBSTR(MES_ANO,1,2)='01' THEN 'JANEIRO'
WHEN SUBSTR(MES_ANO,1,2)='02' THEN 'FEVEREIRO'
WHEN SUBSTR(MES_ANO,1,2)='03' THEN 'MARÇO'
WHEN SUBSTR(MES_ANO,1,2)='04' THEN 'ABRIL'
WHEN SUBSTR(MES_ANO,1,2)='05' THEN 'MAIO'
WHEN SUBSTR(MES_ANO,1,2)='06' THEN 'JUNHO'
WHEN SUBSTR(MES_ANO,1,2)='07' THEN 'JULHO'
WHEN SUBSTR(MES_ANO,1,2)='08' THEN 'AGOSTO'
WHEN SUBSTR(MES_ANO,1,2)='09' THEN 'SETEMBRO'
WHEN SUBSTR(MES_ANO,1,2)='10' THEN 'OUTUBRO'
WHEN SUBSTR(MES_ANO,1,2)='11' THEN 'NOVEMBRO'
WHEN SUBSTR(MES_ANO,1,2)='12' THEN 'DEZEMBRO'
END MES,
SUBSTR(MES_ANO,4,4) ANO,

TO_DATE('01/'||MES_ANO,'DD/MM/YYYY') DIA_UM,

MES_ANO, CODIGO SEGMENTO,TRIM(IMDSC1) DSC, CONCATENADO, SUM(CONSUMO) CONSUMO  ,TRIM(CL.DRDL01) CLASSE , TRIM(SU.DRDL01) SUBCLASSE


FROM (

SELECT 
TO_cHAR(TIPO) TIPO,
FILIAL,
MES_ANO, 
CODIGO,
MES_ANO||CODIGO CONCATENADO,
SUM(NVL(CONSUMO,0)) CONSUMO
FROM (
SELECT
A.TIPO,
A.FILIAL,
A.MES||'/'||A.ANO MES_ANO,
A.SEG CODIGO,
CASE 
WHEN A.SEG=B.SEG THEN (NVL(A.QTD,0)+NVL(B.QTD,0))*-1
ELSE A.QTD *-1
END CONSUMO

FROM (
SELECT 
CASE WHEN NVL(SUBSTR(trim(ILMCU),7,2),'0') NOT IN ('V2') THEN 'INTERNO' ELSE 'TERCEIROS' END TIPO,
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'MM') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'MM') END  MES,
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'YYYY') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'YYYY') END  ANO,
TRIM(IMSEG1) AS SEG,

ILKCO CIA ,
TRIM(ILMCU) AS FILIAL,
ILDOC,
ILDOCO,
ILDCTO,
ILDCT,
SUM(DECODE(ILTRUM,IMUOM1,(ILTRQT)/10000,DECODE(UMCONV,0,1,(UMCONV/10000000)*           (ILTRQT)/10000))) QTD
FROM PRODDTA.F4111
LEFT JOIN PRODDTA.F4101  ON ILITM=IMITM
LEFT OUTER JOIN PRODDTA.F41002 C ON IMITM = UMITM AND ILTRUM = UMUM AND IMUOM1 = UMRUM
where ILDCT='IM'

 AND NVL(SUBSTR(trim(ILMCU),7,4),'0') NOT IN ('V301','V302','V303')

AND ILLITM NOT LIKE '%*%'

AND IMSRP5='MP'
AND TRIM(ILLOCN) LIKE '3767%'
GROUP BY 
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'MM') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'MM') END  ,
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'YYYY') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'YYYY') END  ,
TRIM(IMSEG1)  ,TRIM(ILMCU) ,ILDOC,ILDOCO,ILDCTO,ILKCO,ILDCT
)A

LEFT JOIN (
SELECT 
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'MM') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'MM') END  MES,
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'YYYY') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'YYYY') END  ANO,
TRIM(IMSEG1) AS SEG,

ILKCO CIA ,
TRIM(A.ILMCU) AS FILIAL,
A.ILDOC,
A.ILDOCO,
A.ILDCTO,
A.ILDCT,
SUM(DECODE(A.ILTRUM,IMUOM1,(A.ILTRQT)/10000,DECODE(UMCONV,0,1,(UMCONV/10000000)*           (A.ILTRQT)/10000))) QTD
FROM PRODDTA.F4111 A 
LEFT JOIN PRODDTA.F4101  ON A.ILITM=IMITM
LEFT OUTER JOIN PRODDTA.F41002 C ON IMITM = UMITM AND A.ILTRUM = UMUM AND IMUOM1 = UMRUM
where A.ILDCT='IC'

 AND NVL(SUBSTR(trim(ILMCU),7,4),'0') NOT IN ('V301','V302','V303')

AND ILLITM NOT LIKE '%*%'

AND ILLITM NOT LIKE '%*%'
AND IMSRP5='MP'
GROUP BY 
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'MM') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'MM') END  ,
CASE WHEN NVL(ILDGL,0)='0' THEN TO_CHAR(TO_DATE((ILTRDJ+1900000), 'YYYYDDD'), 'YYYY') ELSE TO_CHAR(TO_DATE((ILDGL+1900000), 'YYYYDDD'), 'YYYY') END  ,
TRIM(IMSEG1) ,TRIM(A.ILMCU) ,A.ILDOC,A.ILDOCO,A.ILDCTO,A.ILKCO,A.ILDCT
)B ON A.SEG=B.SEG AND A.ILDOC=B.ILDOC  AND A.ILDCTO=B.ILDCTO AND A.CIA=B.CIA   AND A.MES=B.MES AND A.ANO=B.ANO 

)
GROUP BY MES_ANO, CODIGO,MES_ANO||CODIGO,FILIAL,TIPO


UNION ALL 


SELECT 
TO_cHAR('REVENDA') TIPO,
TRIM(A.ILMCU) AS FILIAL,
CASE WHEN NVL(A.ILDGL,0)='0' THEN ''  ELSE TO_CHAR(TO_DATE((A.ILDGL+1900000), 'YYYYDDD'), 'MM/YYYY') END MES_ANO,
TRIM(IMSEG1) AS CODIGO,
CASE WHEN NVL(A.ILDGL,0)='0' THEN ''  ELSE TO_CHAR(TO_DATE((A.ILDGL+1900000), 'YYYYDDD'), 'MM/YYYY') END||TRIM(IMSEG1) CONCATENADO,
SUM(DECODE(A.ILTRUM,IMUOM1,(A.ILTRQT)/10000,DECODE(UMCONV,0,1,(UMCONV/10000000)*           (A.ILTRQT/10000)  )))*-1 QTD
FROM PRODDTA.F4111 A 
LEFT JOIN PRODDTA.F4101  ON A.ILITM=IMITM
LEFT OUTER JOIN PRODDTA.F41002 C ON IMITM = UMITM AND A.ILTRUM = UMUM AND IMUOM1 = UMRUM
INNER JOIN PRODDTA.F0101 ON TO_CHAR(ABAN8)=(CASE WHEN ILAN8='0' THEN '24' ELSE TO_CHAR(ILAN8) END )
where A.ILDCT='NS'

AND ILDCTO  IN  ( 'SG','SX','V5','SD','SF','S3','S7','V7','V8','VA','VH','VI','VO','VZ','VY','VN','DO','VQ')

 AND NVL(SUBSTR(trim(ILMCU),7,4),'0') NOT IN ('V301','V302','V303')
and trim(ILMCU) like '6%'
AND ILLITM NOT LIKE '%*%'

AND IMSRP5='MP'
GROUP BY CASE WHEN NVL(A.ILDGL,0)='0' THEN ''  ELSE TO_CHAR(TO_DATE((A.ILDGL+1900000), 'YYYYDDD'), 'MM/YYYY') END  , TRIM(IMSEG1)	,TRIM(A.ILMCU)

  
)
INNER JOIN PRODDTA.F4101 ON TRIM(IMLITM)=TRIM(CODIGO)
LEFT JOIN PRODCTL.F0005 CL ON TRIM(IMSRP1)=TRIM(CL.DRKY) AND TRIM(CL.DRSY)='41' AND TRIM(CL.DRRT)='S1' 
LEFT JOIN PRODCTL.F0005 SU ON TRIM(IMSRP2)=TRIM(SU.DRKY) AND TRIM(SU.DRSY)='41' AND TRIM(SU.DRRT)='S2' 
INNER  JOIN PRODDTA.F0006  ON TRIM(MCMCU)=TRIM(FILIAL)
GROUP BY MES_ANO, CODIGO, CONCATENADO ,TRIM(CL.DRDL01)  , TRIM(SU.DRDL01) 
,CASE 
WHEN SUBSTR(MES_ANO,1,2)='01' THEN 'JANEIRO'
WHEN SUBSTR(MES_ANO,1,2)='02' THEN 'FEVEREIRO'
WHEN SUBSTR(MES_ANO,1,2)='03' THEN 'MARÇO'
WHEN SUBSTR(MES_ANO,1,2)='04' THEN 'ABRIL'
WHEN SUBSTR(MES_ANO,1,2)='05' THEN 'MAIO'
WHEN SUBSTR(MES_ANO,1,2)='06' THEN 'JUNHO'
WHEN SUBSTR(MES_ANO,1,2)='07' THEN 'JULHO'
WHEN SUBSTR(MES_ANO,1,2)='08' THEN 'AGOSTO'
WHEN SUBSTR(MES_ANO,1,2)='09' THEN 'SETEMBRO'
WHEN SUBSTR(MES_ANO,1,2)='10' THEN 'OUTUBRO'
WHEN SUBSTR(MES_ANO,1,2)='11' THEN 'NOVEMBRO'
WHEN SUBSTR(MES_ANO,1,2)='12' THEN 'DEZEMBRO'
END ,
SUBSTR(MES_ANO,4,4) ,TRIM(IMDSC1),TO_DATE('01/'||MES_ANO,'DD/MM/YYYY'),FILIAL,TIPO,TRIM(MCDL01) 