SELECT 
    TO_CHAR(TO_NUMBER(TO_CHAR(data, 'MM'))) AS MES,
    TO_CHAR(data, 'YY') AS ANO,
    TO_CHAR(TRIM(BUSINESS_UNIT)) AS CLASSE,
    CASE
        WHEN BUSINESS_UNIT='REVENDA' THEN to_char(trim(TECNOLOGIA))
    END AS SUBCLASSE,
    SUM(QTD) AS QTD,
    SUM(RECEITA_BRUTA_M_TOTAL) AS RECEITA_BRUTA_M_TOTAL,
    SUM(RECEITA_LIQUIDA_M_TOTAL) AS RECEITA_LIQUIDA_M_TOTAL,
    SUM(CUSTO_GERENCIAL * QTD) AS CUSTO_GERENCIAL_TOTAL,
    SUM(ICMS_TOTAL) AS ICMS_TOTAL,
    SUM(CUSTO_EMB * QTD) AS CUSTO_EMBALAGEM_TOTAL,
    TO_CHAR(trim(CENTRO)) AS CENTRO
    ,0 as VALOR_RECEBER
    ,0 as VALOR_RECEBIDO
FROM PUB_JDE_SALES  
LEFT JOIN (
    SELECT 
        DISTINCT  
        CICO AS cia,
        TRIM(IMSEG1) AS SEGMENT,
        TRIM(CIMCU) AS CENTRO
    FROM 
        proddta.F5549402 A
    INNER JOIN proddta.f4101 B ON CISRP1=imsrp1 AND CISRP2=imsrp2  
    WHERE NOT EXISTS (SELECT 1 FROM PRODDTA.F5549402 C WHERE TRIM(C.CISEG1)=TRIM(B.IMLITM) AND TRIM(C.CISEG1) IS NOT NULL)
    AND TRIM(CISRP5) IS NULL AND TRIM(CISEG1) IS NULL 
    AND TRIM(IMSRP5) IN ('PA','MP')
    AND IMLITM NOT LIKE '%.%'

    UNION

    SELECT 
        DISTINCT  
        CICO AS cia,
        TRIM(IMSEG1) AS SEGMENT,
        TRIM(CIMCU) AS CENTRO 
    FROM 
        proddta.F5549402 A
    INNER JOIN proddta.f4101 B ON IMLITM=CISEG1 AND TRIM(CISEG1) IS NOT NULL 
    WHERE TRIM(CISRP5) IS NULL	 
    AND TRIM(IMSRP5) IN ('PA','MP')
    AND IMLITM NOT LIKE '%.%'
) ON SUBSTR(UN_NEG,1,2)=SUBSTR(cia,1,2) AND SEGMENT=SEGMENTO 
WHERE  INTERCOMPANY IS NULL AND TRIM(CLIENTE) NOT LIKE '%CHILE%'
GROUP BY 
    TO_CHAR(TO_NUMBER(TO_CHAR(data, 'MM'))),
    TO_CHAR(data, 'YY'),
    TRIM(BUSINESS_UNIT), 
    CASE WHEN BUSINESS_UNIT='REVENDA' THEN to_char(trim(TECNOLOGIA)) END,
    TO_CHAR(trim(CENTRO))

UNION ALL

SELECT distinct
    TO_CHAR(D.MES) AS MES,
    TO_CHAR(D.ANO) AS ANO, 
    to_char(trim(srp1.DRDL01)) AS CLASSE,
    CASE WHEN srp1.DRDL01 = 'REVENDA' THEN to_char(TRIM(srp2.DRDL01))
    END AS SUBCLASSE,
    0 AS QTD, 
    0 AS RECEITA_BRUTA_M_TOTAL,  
    0 AS RECEITA_LIQUIDA_M_TOTAL,  
    0 AS CUSTO_GERENCIAL_TOTAL,  
    0 AS ICMS_TOTAL,  
    0 AS CUSTO_EMBALAGEM_TOTAL, 
    TRIM(TO_CHAR(D.CENTRO)) AS CENTRO,
    SUM(D.VALOR_RECEBER) as VALOR_RECEBER
    ,SUM(D.VALOR_RECEBIDO) as VALOR_RECEBIDO
FROM 
    proddta.F5549402 A
left JOIN 
    PRODCTL.F0005 srp1 
    ON srp1.DRSY = '41' 
    AND srp1.DRRT = 'S1' 
    AND TRIM(A.CISRP1) = TRIM(srp1.DRKY)
left JOIN 
    PRODCTL.F0005 srp2 
    ON srp2.DRSY = '41' 
    AND srp2.DRRT = 'S2' 
    AND TRIM(A.CISRP2) = TRIM(srp2.DRKY)
RIGHT JOIN PUBDB.DESPDEL D ON TRIM(A.CIMCU) = CENTRO
where srp1.DRDL01 is not null
group by A.CIMCU, srp1.DRDL01,srp2.DRDL01,D.CENTRO,TO_CHAR(D.MES),TO_CHAR(D.ANO)