
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PUBDB"."ESTRUTURA_CONTAS_EPM" ("NIVEL", "CIA", "CONTA_PAI", "CONTA", "DSC") AS 
  select 
DISTINCT 
'7' NIVEL,
GMCO CIA,
CASE WHEN  TO_CHAR(substr(trim(TRIM(GMOBJ)||'.'||TRIM(GMSUB)),1,6))='550000' THEN TO_CHAR('451100')  ELSE TO_CHAR(substr(trim(TRIM(GMOBJ)||'.'||TRIM(GMSUB)),1,6)) END  CONTA_PAI,
TRIM(GMOBJ)||'.'||TRIM(GMSUB) CONTA,
TRIM(GMDL01) DSC

from proddta.f0901 
WHERE GMMCU!='          MD' AND GMLDA='7'


UNION ALL

SELECT 
DISTINCT
'6' NIVEL,
GMCO CIA,
CASE WHEN GMOBJ='422200' THEN TO_CHAR('421000')     
when SUBSTR(GMOBJ,1,4)='1125' THEN TO_CHAR('112500')    
when SUBSTR(GMOBJ,1,4) IN ('1128','1129') THEN TO_CHAR('112800')  

ELSE TO_CHAR(substr(GMOBJ,1,3)||'000') END CONTA_PAI,
TRIM(GMOBJ) CONTA,
TRIM(GMDL01) DSC
from proddta.f0901 
WHERE GMMCU!='          MD' AND GMLDA='6'



UNION ALL

SELECT 
DISTINCT 
'5' NIVEL,
GMCO CIA,
TO_CHAR(substr(GMOBJ,1,2)||'0000')  CONTA_PAI,
TRIM(GMOBJ) CONTA,
TRIM(GMDL01) DSC
from proddta.f0901 
WHERE GMMCU!='          MD' AND GMLDA='5'


UNION ALL

SELECT 
DISTINCT 
'4' NIVEL,
GMCO CIA,
TO_cHAR(substr(GMOBJ,1,1)||'00000' ) CONTA_PAI,
TRIM(GMOBJ) CONTA,
TRIM(GMDL01) DSC
from proddta.f0901 
WHERE GMMCU!='          MD' AND GMLDA='4'


UNION ALL

SELECT 
DISTINCT 
'3' NIVEL,
GMCO CIA,
'0'  CONTA_PAI,
TRIM(GMOBJ) CONTA,
TRIM(GMDL01) DSC
from proddta.f0901 
WHERE GMMCU!='          MD' AND GMLDA='3'

ORDER BY CIA,CONTA;

