SELECT
 
	CASE 
WHEN MES_ANO LIKE '0%' THEN TO_NUMBER(SUBSTR(MES_ANO,2,1))
ELSE TO_NUMBER(SUBSTR(MES_ANO,1,2))
END MES,
 
SUBSTR(MES_ANO,6,2) ANO	,
	TRIM(BUSINESS_UNIT) CLASSE
	,CASE
	WHEN BUSINESS_UNIT='REVENDA' THEN TECNOLOGIA
	END AS SUBCLASSE
	,nvl(CENTRO,'X') CENTRO

	,SUM(QTD) QTD
	 ,SUM(RECEITA_BRUTA_M_TOTAL) RECEITA_BRUTA_M_TOTAL 
    ,SUM(RECEITA_LIQUIDA_M_TOTAL) RECEITA_LIQUIDA_M_TOTAL 
	,SUM(CUSTO_GERENCIAL * QTD)  CUSTO_GERENCIAL_TOTAL
	,SUM(ICMS_TOTAL) ICMS_TOTAL
	,SUM(CUSTO_EMB * QTD) CUSTO_EMBALAGEM_TOTAL

 
	
FROM PUBDB.PUB_JDE_SALES
 
LEFT JOIN (
SELECT 
DISTINCT  
CICO cia,
TRIM(IMSEG1) SEGMENT ,
TRIM(CIMCU) CENTRO
 
FROM 
    proddta.F5549402 A
inner join proddta.f4101 B on CISRP1=imsrp1 and CISRP2=imsrp2  
 
WHERE NOT EXISTS (SELECT 1 FROM PRODDTA.F5549402 C  WHERE  TRIM(C.CISEG1)=TRIM(B.IMLITM) AND TRIM(C.CISEG1) IS NOT NULL )
AND TRIM(CISRP5)  IS   NULL  AND TRIM(CISEG1) IS  NULL 
AND TRIM(IMSRP5) IN ('PA','MP')
AND IMLITM NOT LIKE '%.%'
 
 
UNION ALL
 
SELECT 
DISTINCT  
CICO cia,
TRIM(IMSEG1) SEGMENT ,
TRIM(CIMCU) CENTRO 
FROM 
    proddta.F5549402 A
inner join proddta.f4101 B on IMLITM=CISEG1 AND TRIM(CISEG1) IS NOT NULL 
WHERE  TRIM(CISRP5)  IS   NULL	 
AND TRIM(IMSRP5) IN ('PA','MP')
AND IMLITM NOT LIKE '%.%'
) ON SUBSTR(UN_NEG,1,2)=SUBSTR(cia,1,2) AND SEGMENT=SEGMENTO
 
where INTERCOMPANY is NULL 
 
GROUP BY 
	CASE 
WHEN MES_ANO LIKE '0%' THEN TO_NUMBER(SUBSTR(MES_ANO,2,1))
ELSE TO_NUMBER(SUBSTR(MES_ANO,1,2))
END ,
 
SUBSTR(MES_ANO,6,2) 	,
	BUSINESS_UNIT 
	,CASE
	WHEN BUSINESS_UNIT='REVENDA' THEN TECNOLOGIA
	END  
,nvl(CENTRO,'X');

--==================================================================================


SELECT 
KCO
,CIA
,MES
,ANO
,SUM(VALOR_RECEBER) as VALOR_RECEBER
,SUM(VALOR_RECEBIDO) as VALOR_RECEBIDO
,TRIM(CENTRO) AS CENTRO
,FILIAL
,OBJ
,SUB
FROM PUBDB.DESPDEL
WHERE EXISTS (SELECT 1 FROM proddta.F5549402  WHERE TRIM(CENTRO)=TRIM(CIMCU) AND CICO IN ('11000','31000','61000'))
group by
KCO
,CENTRO
,CIA
,MES
,ANO
,VALOR_RECEBER
,VALOR_RECEBIDO
,TRIM(CENTRO)
,FILIAL
,OBJ
,SUB