
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PUBDB"."FATURADO_EPM" ("UN_NEG", "FILIAL2", "TIPO", "ULT_ST", "PROX_STATUS", "DATA", "FATURAMENTO", "DATA_INCLUSAO", "MES", "ANO", "DATA_NECESSIDADE", "TIPO_PEDIDO", "PEDIDO", "LINHA", "CODIGO_CLIENTE", "CLIENTE", "GRUPO_CLIENTE", "UF", "CONDICAO_PAG_CADASTRO", "COND_PAG_PEDIDO", "COD", "DESCRICAO", "UM", "QTD", "PRECO_BRUTO_UNIT", "PRECO_UNITARIO_NET", "CUSTO_GERENCIAL_UNIT", "CUSTO_UNIT", "ICMS_P", "PIS_P", "COFINS_P", "IPI_P", "ST", "DIFAL", "RECEITA_BRUTA_TOTAL", "ICMS_TOTAL", "PIS_TOTAL", "COFINS_TOTAL", "RECEITA_NET_TOTAL", "CUSTO_MATERIAL_TOTAL", "CUSTO_TOTAL", "MARCA_PROPRIA", "CLASSE", "SUB_CLASSE", "SUB_CLASSE2", "COD_TRANSP", "TRANSP", "SOLICITADO_POR", "REFERENCIA_DEV", "COD_VENDEDOR", "VENDEDOR", "IMNA", "LOTE", "ICMS_ENTRADA", "FRETE", "ORIGEM", "VALOR_IPI", "TRIB_SUBST", "DESC_REPASSE", "DESC_ZF", "DESPESA_FRETE", "RECEITA_BRUTA_COM_IPI", "RECEITA_BRUTA", "MARGEM", "PRAZO_MEDIO_PAG", "INTERCOMPANY", "RECEITA_BRUTA_M_TOTAL", "RECEITA_LIQUIDA_M_TOTAL") AS 
  SELECT 
  
  
UN_NEG,
FILIAL2,
TIPO,
ULT_ST,
  
PROX_ST PROX_STATUS,
DATA,
DATA_FATURAMENTO FATURAMENTO,
DATA_INCLUSAO,

CASE
WHEN TO_CHAR(TO_DATE(DATA),'MM')='01' THEN '01'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='02' THEN '02'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='03' THEN '03'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='04' THEN '04'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='05' THEN '05'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='06' THEN '06'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='07' THEN '07'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='08' THEN '08'
WHEN TO_CHAR(TO_DATE(DATA),'MM')='09' THEN '09'
ELSE 
TO_CHAR(TO_DATE(DATA),'MM') END MES,
TO_CHAR(TO_DATE(DATA),'YYYY') ANO,
DATA_CLIENTE DATA_NECESSIDADE,
TIPO_PEDIDO,
PEDIDO,
LINHA,
CODIGO_CLIENTE,
CLIENTE,
GRUPO_ECO GRUPO_CLIENTE,
UF,
CONDICAO_PAG_CADASTRO,
COND_PAG_PEDIDO,
COD,
DESCRICAO,
UM,
QTD,

PRECO_UNITARIO PRECO_BRUTO_UNIT,
PRECO_UNITARIO_NET,
MATERIAL CUSTO_GERENCIAL_UNIT,
CUSTO_UNITARIO CUSTO_UNIT,
FDTXR1/100000 ICMS_P,
PIS.TDBRTXR/100000 PIS_P, 
COFINS.TDBRTXR/100000 COFINS_P, 
FDTXR2/100000 IPI_P,
ST, 
DIFAL,
RECEITA_BRUTA_TOTAL,
FDBICM/100 ICMS_TOTAL,
PIS.TDBRTXA/100 PIS_TOTAL,
COFINS.TDBRTXA/100 COFINS_TOTAL,
RECEITA_NET_TOTAL,
CUSTO_MATERIAL_TOTAL,
CUSTO_TOTAL_2 CUSTO_TOTAL,
TRIM(SRP5.DRDL01)  AS MARCA_PROPRIA	,
BUSINESS_UNIT CLASSE,
CASE
WHEN BUSINESS_UNIT='REVENDA' THEN TO_CHAR(TECNOLOGIA)
ELSE ''
END SUB_CLASSE,
TECNOLOGIA SUB_CLASSE2,
COD_TRANSP,
TRANSP,
SOLICITADO SOLICITADO_POR,
REFERENCIA_DEV,
SUBSTR(VENDEDOR,1,INSTR(VENDEDOR,'-')-1) COD_VENDEDOR,
SUBSTR(VENDEDOR,INSTR(VENDEDOR,'-')+1,20) VENDEDOR,
IMNA,
LOTE,
ICMS_ENTRADA,
FRETE,
ORIGEM,
FDBIPI/100 VALOR_IPI,
TRIB_SUBST,
DESC_REPASSE,
DESC_ZF,
NVL(fdBFRT,0)/100+NVL(fdBSEG,0)/100+ nvl(fdBDFN,0)/100 AS DESPESA_FRETE,
FDAEXP/100+FDBIPI/100 RECEITA_BRUTA_COM_IPI,
FDAEXP/100 RECEITA_BRUTA,
(PRECO_UNITARIO_NET-CUSTO_GERENCIAL-CUSTO_EMB )* QTD MARGEM,
PRAZO_MEDIO_PAG,
INTERCOMPANY,
RECEITA_BRUTA_M_TOTAL,
RECEITA_LIQUIDA_M_TOTAL

FROM PUBDB.pub_jde_sales
LEFT JOIN PRODDTA.F7611B ON PEDIDO=FDDOCO AND LINHA=FDLNID/1000 AND TIPO_PEDIDO=FDPDCT AND TRIM(FDMCU)=TRIM(FILIAL) AND FDNXTR NOT BETWEEN '990' AND '998'
LEFT JOIN PRODDTA.F4101 ON FDITM=IMITM
LEFT JOIN PRODCTL.F0005 SRP5 ON trim(SRP5.DRSY)='41' AND TRIM(SRP5.DRRT)='S5' AND TRIM(SRP5.DRKY)=TRIM(IMSRP5)
LEFT OUTER JOIN proddta.F76b011 PIS on PIS.TDBNNF = FDBNNF AND PIS.TDBSER = FDBSER AND PIS.TDN001 = FDN001 AND PIS.TDDCT = FDDCT and PIS.TDUKID = F7611B.FDUKID   AND PIS.TDBRTX = '05'
LEFT OUTER JOIN proddta.F76b011 COFINS on COFINS.TDBNNF = FDBNNF AND COFINS.TDBSER = FDBSER AND COFINS.TDN001 = FDN001 AND COFINS.TDDCT = FDDCT AND COFINS.TDUKID = FDUKID  AND COFINS.TDBRTX = '06'
WHERE TIPO!='CARTEIRA'
and UN_NEG not in ('511000','511001');

