CREATE VIEW HISTORICO_CUSTO_RODRI_V1 AS
SELECT
DATA,
ITEM,
TRIM(B.IMDSC1) AS DESCRICAO_PAI,
TRIM(E.IMSRP1) AS COD_CLASSE,
to_char(trim(srp1.DRDL01)) AS CLASSE,
    CASE WHEN srp1.DRDL01 = 'REVENDA' THEN to_char(TRIM(srp2.DRDL01))
    END AS SUBCLASSE,
LISTA,
CUSTO_REAIS,
CUSTO_ESTRANGEIRO,
CUSTO_SERV,
MOEDA,
CAMBIO,
ULT_PRODUZIDA,
CUSTO_MATERIAL

FROM proddta.TEMP_HISTORICO_CUSTO
INNER join PRODDTA.F4101 B on TRIM(ITEM) = TRIM(B.IMAITM)
INNER JOIN PRODDTA.F3002 A ON A.IXITM = B.IMITM
INNER JOIN PRODDTA.F4101 E ON A.IXKIT = E.IMITM
left JOIN 
    PRODCTL.F0005 srp1 
    ON srp1.DRSY = '41' 
    AND srp1.DRRT = 'S1' 
    AND TRIM(E.IMSRP1) = TRIM(srp1.DRKY)
left JOIN 
    PRODCTL.F0005 srp2 
    ON srp2.DRSY = '41' 
    AND srp2.DRRT = 'S2' 
    AND TRIM(E.IMSRP1) = TRIM(srp2.DRKY)
WHERE to_char(trim(srp1.DRDL01)) IN ('ACRILICOS','BIOCIDA','PARAFINA','PVA','UMECTANTE','PVA-OH')
AND LISTA IN ('M','NET');
