CREATE TABLE STG_ELEK_mgcad_cond_pagto (
ano_base integer ,
cdn_motiv_reprovac_cr integer ,
char_1 varchar(200),
char_2 varchar(200),
check_sum varchar(40),
cod_cond_pag integer NOT NULL,
cod_ven_par varchar(48)NOT NULL,
cod_vencto integer NOT NULL,
dat_vencto_fix date ,
data_1 date ,
data_2 date ,
dec_1 numeric(23),
dec_2 numeric(23),
descricao varchar(60)NOT NULL,
dia_mes_base integer NOT NULL,
dia_mes_venc integer NOT NULL,
dia_sem_base integer NOT NULL,
dia_sem_venc integer NOT NULL,
idi_forma_avaliac_cr integer NOT NULL,
ind_situacao integer NOT NULL,
int_1 integer ,
int_2 integer ,
log_1 varchar(1),
log_2 varchar(1),
log_atual_idx varchar(1)NOT NULL,
log_cond_pagto_mais_negoc varchar(1),
log_dat_fix varchar(1)NOT NULL,
log_reprovac_autom varchar(1),
mes_base integer ,
nr_dias_ante integer ,
nr_dupdes integer ,
nr_ind_finan integer ,
nr_tab_finan integer ,
num_parcelas integer NOT NULL,
per_des_pgan numeric(17),
per_pg_dup varchar(168),
prazos varchar(96)NOT NULL,
qtd_dias_prazo_medio integer ,
)