create table STG_ELEK_mgcad_natur_oper (
aliq_icm_com numeric(17)NOT NULL,
aliquota_icm numeric(17)NOT NULL,
alt_vl_it_terc varchar(1),
atual_estat varchar(1)NOT NULL,
atualiza_of varchar(1)NOT NULL,
auto_ce varchar(1),
auto_cr varchar(1),
auto_ct varchar(1),
auto_est varchar(1),
baixa_estoq varchar(1)NOT NULL,
baixa_ship varchar(1),
calc_auto varchar(1),
cd_registro varchar(4)NOT NULL,
cd_situacao integer NOT NULL,
cd_trib_icm integer NOT NULL,
cd_trib_ipi integer NOT NULL,
cd_trib_iss integer NOT NULL,
cd_vinc_ipi varchar(12),
cdd_perc_retenc_cofins numeric(17)NOT NULL,
cdd_perc_retenc_csll numeric(17)NOT NULL,
cdd_perc_retenc_pis numeric(17)NOT NULL,
char_1 varchar(200),
char_2 varchar(200),
check_sum varchar(40),
cod_canal_venda integer ,
cod_cfop varchar(20)NOT NULL,
cod_cta_ctbl_cust_vda varchar(34)NOT NULL,
cod_cta_ctbl_recta_vendas varchar(34)NOT NULL,
cod_cta_ctbl_transit_vendas varchar(34)NOT NULL,
cod_esp varchar(4)NOT NULL,
cod_livre_1 varchar(200),
cod_livre_2 varchar(200),
cod_mensagem integer ,
cod_model_nf_eletro varchar(16)NOT NULL,
cod_natur_oper_bonif varchar(12),
cod_natur_ref varchar(12),
cod_trib_ii integer ,
consum_final varchar(1)NOT NULL,
credito_ciap varchar(1),
credito_subs varchar(1),
ct_cusven varchar(40)NOT NULL,
ct_recven varchar(40)NOT NULL,
ct_transven varchar(40)NOT NULL,
dat_livre_1 date ,
dat_livre_2 date ,
data_1 date ,
data_2 date ,
dec_1 numeric(23),
dec_2 numeric(23),
denominacao varchar(70)NOT NULL,
dest_red_icms numeric(19),
emite_duplic varchar(1)NOT NULL,
especie_doc varchar(6),
form_cfop varchar(10),
gera_prev_cr varchar(1),
icms_subs_trib numeric(17)NOT NULL,
idi_escrit_fatur_remes integer NOT NULL,
idi_tip_devol_consig integer NOT NULL,
imp_nota varchar(1),
ind_contabilizacao varchar(1),
ind_devolucao_valor varchar(1),
ind_entfut varchar(1),
ind_entreg_futur integer ,
ind_est_crz varchar(1)NOT NULL,
ind_est_mof varchar(1)NOT NULL,
ind_est_qtd varchar(1)NOT NULL,
ind_gera_of varchar(1)NOT NULL,
ind_imprenda varchar(1)NOT NULL,
ind_it_icms varchar(1),
ind_it_sub_dif varchar(1),
ind_nota_propria integer ,
ind_situacao integer NOT NULL,
ind_tipo_vat varchar(1)NOT NULL,
ind_venda_ambulante integer ,
int_1 integer ,
int_2 integer ,
ipi_icm_out varchar(1),
log_1 varchar(1),
log_2 varchar(1),
log_acum_ciap varchar(1)NOT NULL,
log_apurac_retenc varchar(1)NOT NULL,
log_atual_cotas varchar(1),
log_base_ipi varchar(1),
log_biss varchar(1),
log_cofins_despes_import varchar(1),
log_consid_icms_outras varchar(1),
log_contrib_st_antec varchar(1)NOT NULL,
log_cr_st_antec varchar(1)NOT NULL,
log_deduz_desc_zfm_tot_nf varchar(1),
log_emit_remito varchar(1),
log_frete_bipi varchar(1),
log_gera_cre_subst varchar(1),
log_gera_ncredito varchar(1),
log_icms_despes_import varchar(1),
log_icms_despes_import_nfr varchar(1),
log_icms_out_subst varchar(1),
log_icms_presmdo varchar(1),
log_icms_substto_antecip varchar(1)NOT NULL,
log_icms_substto_base_contrib varchar(1)NOT NULL,
log_icms_substto_base_irf_retid varchar(1)NOT NULL,
log_icms_substto_compltar varchar(1)NOT NULL,
log_icms_substto_repas varchar(1)NOT NULL,
log_impr_ipi_danfe varchar(1)NOT NULL,
log_impr_nf_auto varchar(1),
log_impres_autom varchar(1),
log_incid_icms_tot_nfr varchar(1),
log_integr_base_calc_icms_nfr varchar(1),
log_ipi_bicms varchar(1),
log_ipi_contrib_retid varchar(1)NOT NULL,
log_ipi_contrib_social varchar(1)NOT NULL,
log_ipi_imune varchar(1)NOT NULL,
log_ipi_nao_tributad varchar(1)NOT NULL,
log_ipi_out_bsubst varchar(1),
log_ipi_out_tot varchar(1),
log_ipi_outras_contrib_retid varchar(1)NOT NULL,
log_ipi_outras_contrib_social varchar(1)NOT NULL,
log_ipi_suspen_icms varchar(1),
log_livre_1 varchar(1),
log_livre_2 varchar(1),
log_livre_3 varchar(1),
log_livre_4 varchar(1),
log_livre_5 varchar(1),
log_livre_6 varchar(1),
log_memorando varchar(1)NOT NULL,
log_natur_operac_draw varchar(1),
log_natureza_bonif varchar(1),
log_nota_comercio varchar(10),
log_oper_triang varchar(1),
log_operac_transp varchar(1),
log_permite_lote_vencid varchar(1),
Log_picking varchar(1)NOT NULL,
log_pis_despes_import varchar(1),
log_remito_gera_prevcr varchar(1),
log_ret_inss_fonte varchar(1),
log_suspens_impto_import varchar(1),
log_suspens_ipi_import varchar(1),
log_vda_ret varchar(1),
log_vl_it_terc varchar(1),
manut_icm varchar(1)NOT NULL,
manut_ipi varchar(1)NOT NULL,
merc_base_icms integer ,
mercado integer NOT NULL,
modelo_cupom varchar(10),
modelo_docto varchar(4)NOT NULL,
narrativa varchar(4000)NOT NULL,
nat_ativa varchar(1)NOT NULL,
nat_comp varchar(12)NOT NULL,
nat_operacao varchar(12)NOT NULL,
nat_vinculada varchar(12),
nota_rateio varchar(1),
num_livre_1 integer ,
num_livre_2 integer ,
oper_terc integer NOT NULL,
per_des_icms numeric(20)NOT NULL,
per_fin_soc varchar(24)NOT NULL,
per_sub_tri numeric(17),
perc_desc_zf numeric(17),
perc_red_icm numeric(19)NOT NULL,
perc_red_ipi numeric(17)NOT NULL,
perc_red_iss numeric(17)NOT NULL,
preco_saida integer NOT NULL,
sc_cusven varchar(40)NOT NULL,
sc_recven varchar(40)NOT NULL,
sc_transven varchar(40)NOT NULL,
subs_trib varchar(1)NOT NULL,
terceiros varchar(1)NOT NULL,
tipo integer ,
tipo_compra integer NOT NULL,
tipo_trib integer ,
tp_base_icm varchar(2)NOT NULL,
tp_oper_terc integer NOT NULL,
tp_rec_desp integer ,
transf varchar(1)NOT NULL,
usa_nota_ent varchar(1),
usa_pick varchar(1),
uso integer ,
val_livre_1 numeric(23),
val_livre_2 numeric(23),
val_perc_desc_cofins_zfm numeric(20)NOT NULL,
val_perc_desc_pis_zfm numeric(20)NOT NULL,
val_perc_impto_renda numeric(17),
val_perc_sat numeric(17)NOT NULL,
val_perc_senar numeric(17)NOT NULL,
var_val_it_terc numeric(19),
venda_ativo varchar(1)NOT NULL,
)