CREATE TABLE STG_ELEK_mgcad_emitente(
agencia varchar(16)NOT NULL,
agente_retencao varchar(1),
atividade varchar(24)NOT NULL,
bairro varchar(60)NOT NULL,
bairro_cob varchar(60)NOT NULL,
bonificacao numeric(18)NOT NULL,
bx_acatada integer NOT NULL,
caixa_postal varchar(20),
calcula_multa varchar(1)NOT NULL,
categoria varchar(6)NOT NULL,
cdn_atraso_max integer ,
cep varchar(24)NOT NULL,
cep_cob varchar(24),
cgc varchar(38),
cgc_cob varchar(38)NOT NULL,
char_1 varchar(4000),
char_2 varchar(200),
check_sum varchar(40),
cidade varchar(50)NOT NULL,
cidade_cob varchar(50)NOT NULL,
cn_codigo varchar(40),
cod_banco integer NOT NULL,
cod_cacex varchar(40)NOT NULL,
cod_canal_venda integer ,
cod_classif_cliente integer ,
cod_classif_fornec integer ,
cod_cond_pag integer ,
cod_email_nfe varchar(1000),
cod_emitente integer NOT NULL,
cod_entrega varchar(24),
cod_gr_cli integer NOT NULL,
cod_gr_forn integer ,
cod_inscr_inss varchar(40),
cod_isencao integer ,
cod_mensagem integer NOT NULL,
cod_parceiro_edi integer ,
cod_pulmao varchar(10),
cod_rep integer NOT NULL,
cod_repres_imp integer ,
cod_suframa varchar(40)NOT NULL,
cod_tax integer ,
cod_tip_ent integer ,
cod_transp integer NOT NULL,
compr_period numeric(17),
conta_corren varchar(40)NOT NULL,
contato varchar(52)NOT NULL,
contrib_icms varchar(1),
cx_post_cob varchar(20),
dat_nasc date ,
dat_valid_suframa date ,
data_1 date ,
data_2 date ,
data_implant date NOT NULL,
data_taxa date ,
dec_1 numeric(23),
dec_2 numeric(23),
dias_comp integer ,
dt_atualiza date ,
dt_fim_cred date ,
dt_lim_cred date ,
dt_ult_venda date ,
e_mail varchar(80),
emissao_ped integer ,
emite_bloq varchar(1),
emite_etiq varchar(1)NOT NULL,
end_cobranca integer NOT NULL,
endereco varchar(80)NOT NULL,
endereco_cob varchar(80)NOT NULL,
endereco_cob_text varchar(4000),
endereco2 varchar(80),
endereco_text varchar(4000),
esp_pd_venda integer NOT NULL,
estado varchar(8)NOT NULL,
estado_cob varchar(8)NOT NULL,
estoque integer ,
flag_pag integer ,
forn_exp varchar(1)NOT NULL,
gera_ad varchar(1)NOT NULL,
gera_difer integer NOT NULL,
home_page varchar(80),
hora_fim integer ,
hora_ini integer ,
hra_atualiz varchar(16),
identific integer NOT NULL,
idi_tributac_cofins integer NOT NULL,
idi_tributac_pis integer NOT NULL,
ind_abrange_aval integer ,
ind_apr_cred varchar(1)NOT NULL,
ind_atraso integer NOT NULL,
ind_aval integer NOT NULL,
ind_aval_embarque integer ,
ind_cre_cli integer NOT NULL,
ind_cred_abat varchar(1),
ind_dif_atrs_1 integer NOT NULL,
ind_dif_atrs_2 integer NOT NULL,
ind_div_atraso integer NOT NULL,
ind_emit_retencao integer ,
ind_fat_par varchar(1)NOT NULL,
ind_lib_estoque varchar(1),
ind_licenciador varchar(1),
ind_moeda_tit integer ,
ind_rendiment varchar(1),
ind_sit_emitente integer ,
inf_complementar varchar(24),
ins_banc varchar(16),
ins_est_cob varchar(38)NOT NULL,
ins_estadual varchar(38)NOT NULL,
ins_municipal varchar(38)NOT NULL,
insc_subs_trib varchar(38),
int_1 integer ,
int_2 integer ,
istr integer NOT NULL,
item_cli varchar(1),
lim_adicional numeric(17),
lim_credito numeric(17)NOT NULL,
linha_produt varchar(16)NOT NULL,
log_1 varchar(1),
log_2 varchar(1),
log_beneficiario varchar(1),
log_calcula_pis_cofins_unid varchar(1)NOT NULL,
log_contribt_subst_interm varchar(1)NOT NULL,
log_controla_val_max_inss varchar(1),
log_integr_totvs_colab_vendas varchar(1),
log_nf_eletro varchar(1),
log_optan_cr_presmdo_subst varchar(1)NOT NULL,
log_optan_suspens_ipi varchar(1)NOT NULL,
log_possui_nf_eletro varchar(1)NOT NULL,
mod_prefer integer NOT NULL,
modalidade integer NOT NULL,
modalidade_ap integer NOT NULL,
moeda_libcre integer ,
nat_ope_ext varchar(12),
nat_operacao varchar(12)NOT NULL,
natureza integer NOT NULL,
nom_fantasia varchar(120),
nome_abrev varchar(24)NOT NULL,
nome_emit varchar(160)NOT NULL,
nome_matriz varchar(24)NOT NULL,
nome_mic_reg varchar(24),
nome_tr_red varchar(24),
nr_cheque_devol integer ,
nr_copias_ped integer NOT NULL,
nr_dias integer ,
nr_dias_atraso integer ,
nr_dias_taxa integer ,
nr_mesina integer NOT NULL,
nr_peratr integer NOT NULL,
nr_tab_progr integer ,
nr_tabpre varchar(16)NOT NULL,
nr_titulo integer ,
obs_entrega varchar(4000),
observacoes varchar(4000)NOT NULL,
pais varchar(40)NOT NULL,
pais_cob varchar(40),
per_max_canc numeric(17)NOT NULL,
per_minfat numeric(17),
perc_fat_ped integer NOT NULL,
percent_verba numeric(17)NOT NULL,
percepcao varchar(1),
periodo_devol integer ,
port_prefer integer ,
portador integer NOT NULL,
portador_ap integer NOT NULL,
prog_emit varchar(1),
prox_ad integer NOT NULL,
ramal varchar(24)NOT NULL,
ramal_fac varchar(10),
ramal_fax varchar(10),
ramal_modem varchar(14),
recebe_inf_sci varchar(1),
rend_tribut numeric(17),
resumo_mp integer NOT NULL,
retem_pagto varchar(1)NOT NULL,
short_name varchar(32),
taxa_financ numeric(17)NOT NULL,
telef_fac varchar(30),
telef_modem varchar(30),
telefax varchar(30)NOT NULL,
telefone varchar(64)NOT NULL,
telex varchar(30)NOT NULL,
tip_cob_desp integer ,
tp_desp_padrao integer ,
tp_inspecao integer ,
tp_pagto integer ,
tp_qt_prg integer NOT NULL,
tp_rec_padrao integer ,
tr_ar_valor integer NOT NULL,
user_libcre varchar(24)NOT NULL,
utiliza_verba varchar(1)NOT NULL,
val_quota_media numeric(19),
valor_minimo numeric(17),
ven_domingo integer NOT NULL,
ven_feriado integer NOT NULL,
ven_sabado integer NOT NULL,
vencto_dia_nao_util varchar(1)NOT NULL,
vl_max_devol numeric(17),
vl_min_ad numeric(17),
zip_cob_code varchar(24),
zip_code varchar(24),

)