create table STG_ELEK_mgmov_doc_fiscal (
aliquota_icm numeric(17)NOT NULL,
bairro varchar(60)NOT NULL,
cd_registro varchar(4)NOT NULL,
cd_situacao integer NOT NULL,
cdn_cidade integer NOT NULL,
cdn_modalid_transp integer NOT NULL,
cdn_moed_siscomex integer NOT NULL,
cdn_tip_conhecto integer NOT NULL,
cep varchar(24)NOT NULL,
cgc varchar(38),
char_1 varchar(4000),
char_2 varchar(4000),
check_sum varchar(40),
cidade varchar(50)NOT NULL,
cidade_cif varchar(50),
cod_cfop varchar(20)NOT NULL,
cod_chave_aces_nf_eletro varchar(120),
cod_cnpj_transpdor varchar(38),
cod_comprov_export varchar(40)NOT NULL,
cod_conhecto varchar(40)NOT NULL,
cod_des_merc integer ,
cod_emitente integer NOT NULL,
cod_ender_entreg varchar(24),
cod_estabel varchar(10)NOT NULL,
cod_inscr_estad_transpdor varchar(38),
cod_livre_1 varchar(200)NOT NULL,
cod_livre_2 varchar(200),
cod_mensagem integer ,
cod_moeda integer ,
cod_observa integer NOT NULL,
cod_pais_siscomex varchar(20)NOT NULL,
cod_placa varchar(78),
cod_rejeicao integer ,
cod_solicit_despch varchar(40)NOT NULL,
cod_uf_placa varchar(18),
cod_uf_transpdor varchar(4),
cod_vencto integer ,
dat_comprov_export date ,
dat_conhecto date ,
dat_livre_1 date ,
dat_livre_2 date ,
dat_reg_export date ,
dat_solicit_despch date ,
data_1 date ,
data_2 date ,
dec_1 numeric(23),
dec_2 numeric(23),
des_decla_import varchar(40)NOT NULL,
dsl_dados_compl varchar(4000),
dt_docto date ,
dt_embarque date ,
dt_emis_doc date NOT NULL,
dt_impl date NOT NULL,
dt_ult_alt date ,
emite_duplic varchar(1)NOT NULL,
endereco varchar(80)NOT NULL,
endereco_text varchar(4000),
esp_docto varchar(6)NOT NULL,
estado varchar(8)NOT NULL,
idi_sit_nf_eletro integer ,
ind_cifob integer ,
ind_icm_ret varchar(1),
ind_imprenda varchar(1)NOT NULL,
ind_ori_doc integer ,
ind_sit_doc integer NOT NULL,
ind_tip_nota integer NOT NULL,
ins_estadual varchar(38)NOT NULL,
int_1 integer ,
int_2 integer ,
ipi_deb_cre numeric(17)NOT NULL,
log_1 varchar(1),
log_2 varchar(1),
log_averb varchar(1)NOT NULL,
log_bxa_estoq varchar(1)NOT NULL,
log_livre_1 varchar(1),
log_livre_2 varchar(1),
log_livre_3 varchar(1),
log_livre_4 varchar(1),
log_livre_5 varchar(1),
log_livre_6 varchar(1),
manut_icm_it varchar(1)NOT NULL,
manut_ipi_it varchar(1)NOT NULL,
nat_operacao varchar(12)NOT NULL,
nivel_restituicao varchar(2),
nome_ab_emi varchar(24)NOT NULL,
nome_transp varchar(24),
nr_doc_fis varchar(32)NOT NULL,
nr_fatura varchar(32),
nr_re varchar(24),
nr_redespacho varchar(22),
nr_siscomex varchar(40),
num_livre_1 integer ,
num_livre_2 integer ,
observacao varchar(4000)NOT NULL,
pais varchar(40)NOT NULL,
pc_desc_icms numeric(17),
pc_restituicao numeric(17),
perc_red_icm numeric(19)NOT NULL,
perc_red_ipi numeric(17)NOT NULL,
perc_red_iss numeric(17)NOT NULL,
peso_bru_tot numeric(18)NOT NULL,
peso_liq_tot numeric(18)NOT NULL,
placa varchar(20),
preco_saida integer NOT NULL,
qt_volumes integer NOT NULL,
serie varchar(10)NOT NULL,
serie_nota varchar(10),
sigla_emb varchar(6)NOT NULL,
tipo_nat integer ,
tot_desconto numeric(17)NOT NULL,
user_alt varchar(24),
val_base_contrib_social numeric(17)NOT NULL,
val_bc_cofins numeric(17),
val_bc_pis numeric(17),
val_desp_outros numeric(20),
val_despch numeric(17)NOT NULL,
val_livre_1 numeric(23),
val_livre_2 numeric(23),
val_tot_tribut numeric(17),
via_transp integer NOT NULL,
vl_bicms numeric(17),
vl_bipi numeric(17),
vl_biss numeric(17)NOT NULL,
vl_bsubs numeric(17)NOT NULL,
vl_cont_doc numeric(17)NOT NULL,
vl_embalagem numeric(17),
vl_finsocial numeric(17)NOT NULL,
vl_frete numeric(17),
vl_icms numeric(17),
vl_icms_com numeric(17)NOT NULL,
vl_icmsnt numeric(17),
vl_icmsou numeric(17),
vl_icmsub numeric(17)NOT NULL,
vl_ipi numeric(17)NOT NULL,
vl_ipi_devol numeric(17),
vl_ipint numeric(17)NOT NULL,
vl_ipiou numeric(17)NOT NULL,
vl_irf numeric(17)NOT NULL,
vl_iss numeric(17)NOT NULL,
vl_issnt numeric(17)NOT NULL,
vl_issou numeric(17)NOT NULL,
vl_mercad numeric(17)NOT NULL,
vl_pis numeric(17)NOT NULL,
vl_redespacho numeric(17),
vl_seguro numeric(17)
)