CREATE TABLE STG_ELEK_mgmov_item_doc_est(
aliquota_icm numeric(17)NOT NULL,
aliquota_ipi numeric(17)NOT NULL,
aliquota_iss numeric(17)NOT NULL,
atualiza_pa varchar(1)NOT NULL,
baixa_ce varchar(1)NOT NULL,
base_cofins_subs numeric(17)NOT NULL,
base_icm varchar(64)NOT NULL,
base_icm_cmi numeric(17)NOT NULL,
base_ipi varchar(64)NOT NULL,
base_ipi_cmi numeric(17)NOT NULL,
base_iss varchar(64)NOT NULL,
base_iss_cmi numeric(17)NOT NULL,
base_pis numeric(17)NOT NULL,
base_pis_subs numeric(17)NOT NULL,
base_subs varchar(68),
base_subs_cmi numeric(17)NOT NULL,
c_nr_invoice varchar(20),
cd_trib_icm integer NOT NULL,
cd_trib_ipi integer NOT NULL,
cd_trib_iss integer NOT NULL,
cdn_devolucao integer ,
cdn_impto_retid integer NOT NULL,
char_1 varchar(4000),
char_2 varchar(4000),
check_sum varchar(40),
class_fiscal varchar(20)NOT NULL,
cod_barras varchar(100),
cod_cfop_saida varchar(10),
cod_depos varchar(6)NOT NULL,
cod_despesa varchar(24),
cod_disposicao varchar(6),
cod_emit_benef integer ,
cod_emit_terc integer ,
cod_emitente integer NOT NULL,
cod_esp varchar(4),
cod_estab_compon varchar(10),
cod_localiz varchar(20),
cod_lote_fabrican varchar(80),
cod_motivo varchar(6),
cod_parc_devol varchar(4),
cod_refer varchar(16)NOT NULL,
cod_roteiro varchar(32),
cod_tax integer ,
cod_tax_isr integer ,
cod_unid_negoc varchar(6),
codigo_rejei integer NOT NULL,
componente varchar(1)NOT NULL,
conta_contabil varchar(40),
cota_moeda varchar(52),
cotacao_alt varchar(68),
cotacao_cmi numeric(23)NOT NULL,
cotacao_fasb numeric(23)NOT NULL,
ct_codigo varchar(40)NOT NULL,
dat_fabricc_lote date ,
dat_valid_lote_fabrican date ,
data date ,
data_1 date ,
data_2 date ,
data_comp date ,
dec_1 numeric(23),
dec_2 numeric(23),
declaracao_import varchar(40)NOT NULL,
desconto varchar(64)NOT NULL,
desconto_cmi numeric(17)NOT NULL,
desconto_me numeric(17),
despesas varchar(64)NOT NULL,
despesas_cmi numeric(17)NOT NULL,
despesas_me varchar(64),
dt_ent_prev date ,
dt_nota_comp date ,
dt_retorno date ,
dt_vali_lote date ,
emite_comp integer NOT NULL,
encerra_pa varchar(1)NOT NULL,
est_cob varchar(10),
etiquetas integer ,
flag_atu integer ,
fn_docto_ap integer ,
fornec_comp integer ,
hora varchar(16),
i_nr_gi integer NOT NULL,
i_seq_inv integer ,
icm_comp_cmi numeric(17)NOT NULL,
icm_complem varchar(64)NOT NULL,
icm_ntr_cmi numeric(17)NOT NULL,
icm_ntrib varchar(64)NOT NULL,
icm_out_cmi numeric(17)NOT NULL,
icm_outras varchar(64)NOT NULL,
id_bem numeric(15)NOT NULL,
idi_tributac_cofins integer NOT NULL,
idi_tributac_pis integer NOT NULL,
int_1 integer ,
int_2 integer ,
ipi_ntr_cmi numeric(17)NOT NULL,
ipi_ntrib varchar(64)NOT NULL,
ipi_out_cmi numeric(17)NOT NULL,
ipi_outras varchar(64)NOT NULL,
iss_ntr_cmi numeric(17)NOT NULL,
iss_ntrib varchar(64)NOT NULL,
iss_out_cmi numeric(17)NOT NULL,
iss_outras varchar(64)NOT NULL,
it_codigo varchar(32)NOT NULL,
item_pai varchar(32),
log_1 varchar(1),
log_2 varchar(1),
log_fifo_oc varchar(1)NOT NULL,
log_geracao_ncr_ap varchar(1),
log_gerou_ncredito varchar(1)NOT NULL,
log_icm_retido varchar(1)NOT NULL,
log_nota_ajust_import varchar(1),
log_usa_unid_negoc_fifo varchar(1)NOT NULL,
lote varchar(80)NOT NULL,
narrativa varchar(4000)NOT NULL,
nat_comp varchar(12)NOT NULL,
nat_of varchar(12)NOT NULL,
nat_of_comp varchar(12),
nat_operacao varchar(12)NOT NULL,
nat_terc varchar(12),
nivel_restituicao varchar(2),
nom_fabrican varchar(120),
nr_ato_concessorio varchar(40),
nr_docto_ap varchar(32),
nr_ficha integer NOT NULL,
nr_ord_produ integer NOT NULL,
nr_pd_ent integer NOT NULL,
nr_pd_seq integer NOT NULL,
nr_pedcli varchar(24)NOT NULL,
nr_proc_imp varchar(24),
nro_comp varchar(32)NOT NULL,
nro_docto varchar(32)NOT NULL,
nro_docto_terc varchar(32),
num_event_contrat integer ,
num_ord_import integer ,
num_ord_inv integer ,
num_parc_import integer ,
num_pedido integer ,
num_ret_om integer ,
num_seq_rma integer ,
num_sit_trib_icms integer NOT NULL,
numero_ordem integer NOT NULL,
op_codigo integer ,
origem integer ,
parcela integer NOT NULL,
pc_restituicao numeric(17),
perc_isr numeric(17),
perc_sales_tax numeric(17),
perc_vat numeric(17),
peso_bruto_item numeric(20),
peso_liquido numeric(20)NOT NULL,
peso_liquido_item numeric(20),
pr_mob_cmi numeric(19),
pr_total varchar(96)NOT NULL,
pr_total_cmi numeric(17)NOT NULL,
pr_unit_cmi numeric(20),
pre_unit_mob varchar(72),
preco_fatura numeric(17),
preco_total varchar(64)NOT NULL,
preco_total_alt varchar(64),
preco_total_me numeric(19),
preco_unit varchar(72)NOT NULL,
preco_unit_me numeric(20),
qt_do_forn numeric(19)NOT NULL,
qt_etiquetas integer ,
qt_real numeric(19)NOT NULL,
qt_saldo numeric(19),
quant_conf numeric(19)NOT NULL,
quantidade numeric(19)NOT NULL,
reabre_pa varchar(1)NOT NULL,
reabre_pd varchar(1)NOT NULL,
sc_codigo varchar(40)NOT NULL,
seq_comp integer ,
seq_evento integer NOT NULL,
seq_terc integer ,
sequencia integer NOT NULL,
serie_comp varchar(10)NOT NULL,
serie_docto varchar(10)NOT NULL,
serie_terc varchar(10),
sit_item integer ,
un varchar(4)NOT NULL,
usuario varchar(24),
val_aduana_cofins numeric(20),
val_aduana_pis numeric(20),
val_aliq_cofins numeric(17)NOT NULL,
val_aliq_ext_cofins numeric(17)NOT NULL,
val_aliq_ext_icms numeric(17)NOT NULL,
val_aliq_ext_ipi numeric(17),
val_aliq_ext_pis numeric(17)NOT NULL,
val_aliq_impto_import numeric(17),
val_aliq_impto_retid numeric(17)NOT NULL,
val_aliq_pis numeric(17)NOT NULL,
val_base_calc_cofins numeric(17)NOT NULL,
val_base_st_antec numeric(17),
val_cofins numeric(17)NOT NULL,
val_cofins_cmi numeric(17)NOT NULL,
val_cofins_fasb numeric(17)NOT NULL,
val_despes_aduana_cofins numeric(20),
val_despes_aduana_pis numeric(20),
val_impto_retid numeric(17)NOT NULL,
val_impto_retid_me numeric(17)NOT NULL,
val_perc_red_icms numeric(19)NOT NULL,
val_perc_rep_ipi numeric(19)NOT NULL,
val_perc_restocagem numeric(17),
val_reduc_cofins_import numeric(17),
val_reduc_pis_import numeric(17),
val_restocagem numeric(19),
val_sdo_alocad_oc numeric(17),
val_sdo_alocad_terc numeric(17),
val_st_antec numeric(17),
val_unit_cofins_import numeric(17),
val_unit_pis_import numeric(17),
val_unit_vol_cofins_import numeric(17),
val_unit_vol_pis_import numeric(17),
valor_frete numeric(17),
valor_frete_me numeric(17),
valor_icm varchar(64)NOT NULL,
valor_ipi varchar(64)NOT NULL,
valor_iss varchar(64)NOT NULL,
valor_pis numeric(17)NOT NULL,
valor_pis_cmi numeric(17)NOT NULL,
valor_pis_fasb numeric(17)NOT NULL,
vl_cofins_subs numeric(17)NOT NULL,
vl_icm_cmi numeric(17)NOT NULL,
vl_imp_cmi numeric(17)NOT NULL,
vl_imp_impor varchar(64)NOT NULL,
vl_ipi_cmi numeric(17)NOT NULL,
vl_isr numeric(17),
vl_isr_me numeric(17),
vl_iss_cmi numeric(17)NOT NULL,
vl_pis_subs numeric(17)NOT NULL,
vl_subs varchar(68),
vl_subs_cmi numeric(17),
vl_taxa numeric(17),
vl_taxa_me numeric(17),
vl_unit_mob numeric(17)

)