CREATE TABLE STG_ELEK_mgmov_it_nota_fisc(
aliquota_icm NUMBER(17)NOT NULL,
aliquota_ipi NUMBER(17)NOT NULL,
aliquota_ISS NUMBER(17),
aliquota_tax NUMBER(17),
atual_estat varchar(1)NOT NULL,
baixa_estoq varchar(1)NOT NULL,
cd_emitente integer,
cd_sit_desp integer NOT NULL,
cd_trib_icm integer NOT NULL,
cd_trib_ipi integer,
cd_trib_iss integer NOT NULL,
cd_vendedor varchar(24)NOT NULL,
cdd_embarq NUMBER(15)NOT NULL,
char_1 varchar(200),
char_2 varchar(200),
check_sum varchar(40),
class_fiscal varchar(20)NOT NULL,
cod_cta_ctbl_cust_ctbl varchar(34),
cod_cta_ctbl_cust_produt_vendido varchar(34)NOT NULL,
cod_depos varchar2(6)NOT NULL,
cod_est_ven varchar(10)NOT NULL,
cod_estabel varchar(10)NOT NULL,
cod_localiz varchar(20),
cod_ord_compra varchar(30),
cod_refer varchar(16),
cod_servico integer NOT NULL,
cod_sit_tributar_cofins varchar(16)NOT NULL,
cod_sit_tributar_ipi varchar(16)NOT NULL,
cod_sit_tributar_pis varchar(16)NOT NULL,
cod_tax integer,
cod_unid_negoc varchar(6),
cod_vat integer,
codigo_rejei integer NOT NULL,
conh_frete varchar(16),
ct_cuscon varchar(40)NOT NULL,
ct_cusven varchar(40)NOT NULL,
data_1 date,
data_2 date,
dec_1 NUMBER(23),
dec_2 NUMBER(23),
dec_ftconv_unest NUMBER(17),
des_pct_desconto_inform varchar(100),
desc_devol varchar(4000)NOT NULL,
dt_cancela date,
dt_confirma date,
dt_emis_nota date NOT NULL,
dt_retorno date,
emite_duplic varchar(1)NOT NULL,
fat_retro varchar(1)NOT NULL,
idi_forma_calc_cofins integer NOT NULL,
idi_forma_calc_pis integer NOT NULL,
idi_modalid_base_icms integer NOT NULL,
idi_modalid_base_icms_st integer NOT NULL,
idi_modalid_base_ipi integer NOT NULL,
ind_componen integer NOT NULL,
ind_fat_qtfam varchar(1),
ind_icm_ret varchar(1),
ind_imp_desc integer NOT NULL,
ind_imprenda varchar(1)NOT NULL,
ind_origem_fator integer ,
ind_sit_nota integer NOT NULL,
int_1 integer,
int_2 integer,
it_codigo varchar(32)NOT NULL,
it_nota_fisc integer,
log_1 varchar(1),
log_2 varchar(1),
log_preco_unid_medid_estoq varchar(1)NOT NULL,
log_usa_tabela_desconto varchar(1)NOT NULL,
manut_icm_it varchar(1)NOT NULL,
manut_ipi_it varchar(1)NOT NULL,
nat_docum varchar(12),
nat_operacao varchar(12)NOT NULL,
nat_terc varchar(12),
nivel_restituicao varchar(2),
no_ab_vend varchar(24)NOT NULL,
nome_ab_cli varchar(24),
nr_docum varchar(32),
nr_embarque integer,
nr_entrega integer NOT NULL,
nr_ficha_cq integer NOT NULL,
nr_nota_ant varchar(32),
nr_nota_fis varchar(32)NOT NULL,
nr_ord_prod integer ,
nr_ord_produ integer NOT NULL,
nr_ordem integer ,
nr_pedcli varchar(24),
nr_pedido integer NOT NULL,
nr_remito varchar(32),
nr_seq_fat integer NOT NULL,
nr_seq_it_rmt integer,
nr_seq_ped integer,
nr_tabpre varchar(16)NOT NULL,
num_casa_dec_unest integer,
num_romaneio integer,
num_seq_roman integer,
parcela integer,
pc_restituicao NUMBER(17),
per_des_icms NUMBER(20)NOT NULL,
per_des_item NUMBER(20)NOT NULL,
perc_red_icm NUMBER(19),
perc_red_ipi NUMBER(17)NOT NULL,
perc_red_iss NUMBER(17)NOT NULL,
peso_bruto NUMBER(20)NOT NULL,
peso_liq_fat NUMBER(20)NOT NULL,
qt_devolvida varchar(56),
qt_faturada varchar(56)NOT NULL,
referencia_ct varchar(24),
sc_cuscon varchar(40)NOT NULL,
sc_cusven varchar(40)NOT NULL,
ser_remito varchar(10),
serie varchar(10)NOT NULL,
serie_ant varchar(10),
serie_docum varchar(10),
tipo_atend integer,
tipo_con_est integer NOT NULL,
tipo_contr integer NOT NULL,
un_fatur varchar(12)NOT NULL,
val_base_cofins_substto NUMBER(25),
val_base_pis_substto NUMBER(25),
val_desconto varchar(180),
val_desconto_inform NUMBER(25)NOT NULL,
val_desconto_total NUMBER(25),
val_pct_desconto_periodo NUMBER(25),
val_pct_desconto_prazo NUMBER(25),
val_pct_desconto_tab_preco NUMBER(25)NOT NULL,
val_pct_desconto_total NUMBER(25)NOT NULL,
val_perc_icms_diferim NUMBER(17),
val_retenc_cofins NUMBER(20)NOT NULL,
val_retenc_csll NUMBER(20)NOT NULL,
val_retenc_pis NUMBER(20)NOT NULL,
val_sat NUMBER(20)NOT NULL,
val_senar NUMBER(20)NOT NULL,
val_unit_cofins NUMBER(20)NOT NULL,
val_unit_pis NUMBER(20)NOT NULL,
vl_bicms_it NUMBER(17),
vl_bicmsit_e varchar(102),
vl_bipi_it NUMBER(17),
vl_bipiit_e varchar(102),
vl_biss_it NUMBER(17)NOT NULL,
vl_bissit_e varchar(102),
vl_biva_it NUMBER(17),
vl_biva_it_me NUMBER(20),
vl_bsubs_it NUMBER(17)NOT NULL,
vl_bsubsit_e varchar(102),
vl_comp_acum NUMBER(20)NOT NULL,
vl_cuscontab NUMBER(25)NOT NULL,
vl_cuscontab_e varchar(102),
vl_cuscontab_me NUMBER(25)NOT NULL,
vl_desconto NUMBER(25),
vl_desconto_me NUMBER(25),
vl_despes_it NUMBER(17)NOT NULL,
vl_despes_it_me NUMBER(20)NOT NULL,
vl_despesit_e varchar(102),
vl_finsocial NUMBER(17)NOT NULL,
vl_frete_it NUMBER(17),
vl_frete_it_me NUMBER(20),
vl_icms_it NUMBER(17),
vl_icmscmp_it_e varchar(102),
vl_icmscomp_it NUMBER(17),
vl_icmsit_e varchar(102),
vl_icmsnt_it NUMBER(17),
vl_icmsntit_e varchar(102),
vl_icmsou_it NUMBER(17),
vl_icmsouit_e varchar(102),
vl_icmsub_it NUMBER(17)NOT NULL,
vl_icmsubit_e varchar(102),
vl_ipi_dev NUMBER(17)NOT NULL,
vl_ipi_it NUMBER(17)NOT NULL,
vl_ipiit_e varchar(102),
vl_ipint_it NUMBER(17)NOT NULL,
vl_ipintit_e varchar(102),
vl_ipiou_it NUMBER(17)NOT NULL,
vl_ipiouit_e varchar(102),
vl_ir_adic NUMBER(17)NOT NULL,
vl_irf_it NUMBER(17)NOT NULL,
vl_irfit_e varchar(102),
vl_iss_it NUMBER(17)NOT NULL,
vl_issit_e varchar(102),
vl_issnt_it NUMBER(17)NOT NULL,
vl_issntit_e varchar(102),
vl_issou_it NUMBER(17)NOT NULL,
vl_issouit_e varchar(102),
vl_iva_it NUMBER(17),
vl_iva_it_me NUMBER(20),
vl_merc_liq NUMBER(25)NOT NULL,
vl_merc_liq_me NUMBER(25)NOT NULL,
vl_merc_liq_zfm NUMBER(25),
vl_merc_ori NUMBER(25)NOT NULL,
vl_merc_ori_me NUMBER(25)NOT NULL,
vl_merc_sicm NUMBER(25)NOT NULL,
vl_merc_sicm_me NUMBER(25)NOT NULL,
vl_merc_tab NUMBER(25)NOT NULL,
vl_merc_tab_me NUMBER(25)NOT NULL,
vl_mercliq_e varchar(102),
vl_mercori_e varchar(102),
vl_mercsimc_e varchar(102),
vl_merctab_e varchar(102),
vl_pis NUMBER(17)NOT NULL,
vl_precon NUMBER(25)NOT NULL,
vl_precon_e varchar(108),
vl_precon_me NUMBER(25)NOT NULL,
vl_preori NUMBER(25)NOT NULL,
vl_preori_e varchar(108),
vl_preori_me NUMBER(25)NOT NULL,
vl_preori_un_fat NUMBER(20),
vl_pretab NUMBER(25)NOT NULL,
vl_pretab_e varchar(108),
vl_pretab_me NUMBER(25)NOT NULL,
vl_preuni NUMBER(25)NOT NULL,
vl_preuni_e varchar(108),
vl_preuni_me NUMBER(25)NOT NULL,
vl_preuni_zfm NUMBER(25),
vl_reajuste NUMBER(17)NOT NULL,
vl_reajuste_e varchar(108),
vl_reajuste_me NUMBER(20)NOT NULL,
vl_sub_emp NUMBER(17),
vl_tot_item NUMBER(25),
vl_tot_item_me NUMBER(25),
vl_totitem_e varchar(102)
)