CREATE TABLE stgdb.STG_ELEK_mgmov_cotacao_item(
	aliquota_icm NUMBER (17,2),
	aliquota_ii NUMBER (17,2),
	aliquota_ipi NUMBER (17,2),
	aliquota_iss NUMBER (17,2),
	aprovador VARCHAR2 (24),
	atualiza_cp VARCHAR2 (10),
	cdn_fabrican VARCHAR2 (10),
	cdn_pais_orig VARCHAR2 (10),
	cdn_pto_control VARCHAR2 (10),
	char_1 VARCHAR2 (200),
	char_2 VARCHAR2 (1000),
	check_sum VARCHAR2 (40),
	Class_fiscal VARCHAR2 (20),
	cod_comprado VARCHAR2 (24),
	cod_cond_pag VARCHAR2 (10),
	cod_emitente VARCHAR2 (10),
	cod_incoterm VARCHAR2 (10),
	Cod_pto_contr_base VARCHAR2 (10),
	cod_servico VARCHAR2 (10),
	cod_transp VARCHAR2 (10),
	codigo_icm VARCHAR2 (10),
	codigo_ipi VARCHAR2 (10),
	contato VARCHAR2 (80),
	cot_aprovada VARCHAR2 (10),
	dat_preco_base date,
	data_1 date,
	data_2 date,
	data_atualiz date,
	data_cotacao date,
	dec_1 VARCHAR2 (30),
	dec_2 VARCHAR2 (30),
	dias_validade NUMBER (4),
	dt_embarque date,
	dt_entrega date,
	frete VARCHAR2 (10),
	hora_atualiz VARCHAR2 (16),
	ind_orig_entrada VARCHAR2 (10),
	ind_reajuste NUMBER (17,2),
	ind_ret_cotacao VARCHAR2 (10),
	ind_via_envio NUMBER (4),
	int_1 VARCHAR2 (10),
	int_2 VARCHAR2 (10),
	it_codigo VARCHAR2 (32),
	itinerario VARCHAR2 (10),
	log_1 VARCHAR2 (10),
	log_2 VARCHAR2 (10),
	log_gerac_autom_despes VARCHAR2 (10),
	mapa_cotacao VARCHAR2 (10),
	mo_codigo VARCHAR2 (10),
	motivo_apr VARCHAR2 (4000),
	narrativa VARCHAR2 (4000),
	nome_abrev_fabricante VARCHAR2 (24),
	nr_dias_taxa NUMBER (4),
	nr_tab VARCHAR2 (20),
	num_proc_entr_edi VARCHAR2 (10),
	num_proc_envio_edi VARCHAR2 (10),
	numero_ordem VARCHAR2 (10),
	perc_descto NUMBER (20,5),
	possui_reaj VARCHAR2 (10),
	prazo_entreg NUMBER (4),
	pre_unit_for NUMBER (20,5),
	preco_fornec NUMBER (20,5),
	preco_unit NUMBER (20,5),
	reaj_tabela VARCHAR2 (10),
	reajusta_cotacao VARCHAR2 (10),
	Regime_impot NUMBER (4),
	seq_cotac VARCHAR2 (10),
	taxa_financ VARCHAR2 (10),
	un VARCHAR2 (10),
	usuario VARCHAR2 (24),
	valor_descto NUMBER (19,4),
	valor_frete NUMBER (19,4),
	valor_taxa NUMBER (19,4)
);