CREATE TABLE STG_ELEK_mgmov_nota_fiscal (
bairro varchar(60)NOT NULL,
caixa_postal varchar(20),
cd_sit_desp integer NOT NULL,
cd_vendedor varchar(24)NOT NULL,
cdd_embarq numeric(15)NOT NULL,
cep varchar(24)NOT NULL,
cgc varchar(38),
char_1 varchar(4000),
char_2 varchar(4000),
check_sum varchar(40),
cidade varchar(50)NOT NULL,
cidade_cif varchar(50),
cn_codigo varchar(80),
cod_canal_venda integer ,
cod_chave_aces_nf_eletro varchar(120),
cod_cond_pag integer NOT NULL,
cod_dep_ext varchar(6),
cod_des_merc integer ,
cod_emitente integer ,
cod_entrega varchar(24)NOT NULL,
cod_estab_estoq varchar(10),
cod_estab_proces_export varchar(10)NOT NULL,
cod_estabel varchar(10)NOT NULL,
cod_imagem varchar(60),
cod_lacre varchar(244),
cod_mensagem integer ,
cod_placa_2 varchar(16)NOT NULL,
cod_portador integer ,
cod_protoc varchar(30),
cod_rep integer NOT NULL,
cod_rma varchar(32),
cod_rota varchar(24)NOT NULL,
cod_safra varchar(18),
cod_tax integer ,
cod_tax_div integer ,
cod_tax_emb integer ,
cod_tax_fre integer ,
cod_tax_seg integer ,
cod_uf_placa_2 varchar(16)NOT NULL,
cod_usuar_contingen_nf_eletro varchar(24),
cond_redespa varchar(4000)NOT NULL,
data_1 date ,
data_2 date ,
dec_1 numeric(23),
dec_2 numeric(23),
des_espec_volum varchar(120)NOT NULL,
des_pct_desconto_inform varchar(100),
desc_cancela varchar(4000)NOT NULL,
desc_valor_nota numeric(20),
desc_valor_ped numeric(20),
descto1 numeric(17),
descto2 numeric(17),
distancia numeric(16)NOT NULL,
docto_orig varchar(32),
dt_at_ct date ,
dt_at_est date ,
dt_at_ofest date ,
dt_atual_ap date ,
dt_atual_cr date ,
dt_atualiza date ,
dt_cancela date ,
dt_confirma date ,
dt_embarque date ,
dt_emis_nota date NOT NULL,
dt_entr_cli date ,
dt_prvenc date ,
dt_saida date ,
emite_duplic varchar(1)NOT NULL,
endereco varchar(80)NOT NULL,
endereco_text varchar(4000),
esp_docto integer NOT NULL,
estado varchar(8)NOT NULL,
fat_retro varchar(1)NOT NULL,
hr_atualiza varchar(10)NOT NULL,
hr_confirma varchar(10)NOT NULL,
hr_entr_cli varchar(16),
hra_atualiz varchar(16),
hra_emis_nf varchar(16),
identific varchar(24)NOT NULL,
idi_forma_emis_nf_eletro integer NOT NULL,
idi_sit_nf_eletro integer NOT NULL,
ind_contabil varchar(1),
ind_lib_nota varchar(1),
ind_orig_entrada integer ,
ind_sit_nota integer NOT NULL,
ind_tip_nota integer NOT NULL,
ind_tp_frete integer ,
ind_via_envio integer ,
ins_estadual varchar(38)NOT NULL,
int_1 integer ,
int_2 integer ,
invoice_id varchar(2)NOT NULL,
log_1 varchar(1),
log_2 varchar(1),
log_estorn_comis_repres varchar(1),
log_juros_prorate varchar(1)NOT NULL,
log_possui_retenc varchar(1)NOT NULL,
log_usa_tabela_desconto varchar(1)NOT NULL,
log_var_cambial varchar(1),
marca_volume varchar(40)NOT NULL,
mercado integer NOT NULL,
mo_codigo varchar(32),
modalidade integer ,
nat_operacao varchar(12)NOT NULL,
nivel_restituicao varchar(2),
no_ab_reppri varchar(24)NOT NULL,
nome_ab_cli varchar(24)NOT NULL,
nome_ab_reg varchar(24)NOT NULL,
nome_abrev_tri varchar(24),
nome_tr_red varchar(24),
nome_transp varchar(24),
nr_embarque integer ,
nr_fat_retro varchar(32)NOT NULL,
nr_fatura varchar(32),
nr_ind_finan integer NOT NULL,
nr_invoice varchar(32)NOT NULL,
nr_nota_ant varchar(32),
nr_nota_fis varchar(32)NOT NULL,
nr_parcelas integer ,
nr_pedcli varchar(24)NOT NULL,
nr_pedido_nf_orig integer ,
nr_praz_med numeric(17),
nr_proc_exp varchar(24),
nr_resumo integer ,
nr_siscomex varchar(40),
nr_tab_finan integer ,
nr_tabpre varchar(16)NOT NULL,
nr_volumes varchar(20),
nro_nota_orig varchar(32),
nro_proc_entrada integer ,
nro_proc_saida integer ,
num_cx_financ integer ,
num_process_negoc integer ,
num_rma_orig varchar(32),
num_romaneio integer ,
obs_gerada varchar(4000),
observ_nota varchar(4000),
pais varchar(40)NOT NULL,
pc_restituicao numeric(17),
per_des_icms numeric(18)NOT NULL,
perc_desco1 numeric(18),
perc_desco2 numeric(18),
perc_tax_div numeric(17),
perc_tax_emb numeric(17),
perc_tax_fre numeric(17),
perc_tax_seg numeric(17),
peso_bru_tot numeric(18)NOT NULL,
peso_liq_tot numeric(18)NOT NULL,
placa varchar(20),
preco_saida integer NOT NULL,
refer_cr varchar(24),
refer_ct varchar(24),
replica_nf varchar(1),
serie varchar(10)NOT NULL,
serie_ant varchar(10),
serie_orig varchar(10),
tab_ind_fin numeric(20),
tax_desp numeric(17),
tax_div_me numeric(20),
tax_emb numeric(17),
tax_emb_me numeric(20),
tax_fre_me numeric(20),
tax_frete numeric(17),
tax_seg numeric(17),
tax_seg_me numeric(20),
taxa_orig numeric(20)NOT NULL,
taxa_real numeric(20)NOT NULL,
tipo_fat integer NOT NULL,
tp_pedido varchar(4),
tp_preco integer NOT NULL,
uf_placa varchar(4),
user_calc varchar(24),
val_desc_cofins_zfm numeric(20),
val_desc_pis_zfm numeric(20),
val_desconto_total numeric(25),
val_desp_outros numeric(20),
val_desp_outros_inf numeric(20),
val_iof numeric(17),
val_pct_desconto_tab_preco numeric(25)NOT NULL,
val_pct_desconto_total numeric(25)NOT NULL,
val_pct_desconto_valor numeric(25)NOT NULL,
vl_acum_dup numeric(17)NOT NULL,
vl_acum_dup_me numeric(20)NOT NULL,
vl_acumdup_e varchar(108),
vl_comis_nota numeric(17),
vl_comis_nota_me numeric(20),
vl_cotacao_fatur numeric(20),
vl_cotacao_pedido numeric(20),
vl_desconto numeric(17),
vl_desconto_me numeric(20),
vl_embalagem numeric(17),
vl_embalagem_e varchar(108),
vl_embalagem_me numeric(20)NOT NULL,
vl_fatura numeric(17),
vl_fatura_me numeric(20),
vl_frete numeric(17),
vl_frete_e varchar(108),
vl_frete_me numeric(20),
vl_merc_tot_fat numeric(25),
vl_merc_tot_fat_me numeric(25),
vl_mercad numeric(25)NOT NULL,
vl_mercad_e varchar(108),
vl_mercad_me numeric(25)NOT NULL,
vl_seguro numeric(17),
vl_seguro_e varchar(108),
vl_seguro_me numeric(20),
vl_taxa_exp numeric(23),
vl_taxaexp_e varchar(72),
vl_tot_com numeric(17),
vl_tot_com_me numeric(20),
vl_tot_ipi numeric(17),
vl_tot_itens_fat numeric(17),
vl_tot_itens_fat_me numeric(20),
vl_tot_iva numeric(17),
vl_tot_iva_me numeric(20),
vl_tot_nota numeric(25)NOT NULL,
vl_tot_nota_me numeric(25)NOT NULL,
vl_totnota_e varchar(108),
zip_code varchar(24)
)
