create table conciliacao_recebimento(
GMAID	NCHAR(8)
GMMCU	NCHAR(12)
GMOBJ	NCHAR(6)
GMSUB	NCHAR(8)
CONTA_BANCARIA	NCHAR(30)
N_PAGADOR	NUMBER
NOME_ALFA	NCHAR(40)
DT_CONT	DATE
DT_COMP	DATE
DT_CH_ITEM	DATE
VL_PGTO	NUMBER
VL_ABERTO	NUMBER
OBS	NCHAR(30)
PEDIDO	VARCHAR2(70)
CIA	NCHAR(5)
INST_PGTO	NCHAR(1)
DT_ATUALZ	DATE
N_LOTE	NUMBER
DT_LOTE	DATE
ID_PGTO	NUMBER
COD_EST	NCHAR(1)
ID_USUARIO	NCHAR(10)
COUNTROW	NUMBER
)