CREATE TABLE PUBDB.JDE_SALES_CHILE(
  NOTA Number (15),
  COD_GERAL_1 Number (8),
  CLIENTE varchar2(40),
  CODIGO varchar2(25),
  DESCRICAO varchar2(30),
  UNIDADE varchar2(2),
  QUANTIDADE Numeric (15),
  VALOR_UNITARIO Number(19,2),
  TOTAL Number(19,9),
  VALOR_UNITARIO_BRL Number(19,9),
  TOTAL_BRL Number(19,9),
  EMISSAO date,
  RTH76IDPT varchar2(20),
  FILIAL varchar2(12),
  VENCIMENTO varchar2(30),
  CIDADE_TRANSP varchar2(30),
  REPRESENTATE varchar2(50),
  COMISSAO Number(19,9),
  VALOR_COMISSAO Number(19,9),
  FILIAL_PEDIDO varchar2(12),
  PEDIDO varchar2(30),
  PEDIDO2 Number(8),
  COD_GERAL Number(8),
  COMPANHIA varchar2(30),
  TIPO_DOC varchar2(2),
  IMPOSTO Number(19,9),
  CIDADE varchar2(30),
  ESTADO varchar2(3),
  PAIS varchar2(30),
  TAXA_DOLAR Number(15),
  VALOR_UNITARIO_DOLAR Number(19,9),
  TOTAL_DOLAR Number(19,9),
  VALOR_TOTAL_DOLAR Number(19,9),
  LOTE varchar2(30),
  FRETE varchar2(3),
  EMBALAGEM varchar2(30),
  CLASSE_MERCADORIA varchar2(30),
  SUB_CLASSE varchar2(30),
  SUBCLASSE_MERCADORIA varchar2(30),
  REF_EXP varchar2(30),
  SDLNID Number(10,3),
  MOEDA varchar2(3),
  CRIACAO date,
  ROTULO varchar2(10),
  USUARIO varchar2(20)
 )