CREATE TABLE STG_ELEK_MGMOV_MEDICAO_CONTRAT (
char_1	varchar	(200),
char_2	varchar	(200),
check_sum	varchar	(40),
cod_estabel	varchar	(10),
dat_medicao	date,
dat_prev_medicao	date,
dat_receb	date,
data_1	date,
data_2	date,
dec_1	numeric	(23,8),
dec_2	numeric	(23,8),
ep_codigo	varchar	(6),
hra_medicao	varchar	(16),
ind_sit_medicao	varchar	(10),
int_1	varchar	(10),
int_2	varchar	(10),
it_codigo	varchar	(32),
log_1	varchar	(10),
log_2	varchar	(10),
log_rec_medicao	varchar	(10),
nr_contrato	varchar	(10),
nr_ord_produ	varchar	(10),
num_nota	varchar	(10),
num_ord_inv	varchar	(10),
num_ord_invest	varchar	(10),
num_seq_event	varchar	(10),
num_seq_item	varchar	(10),
num_seq_medicao	varchar	(10),
numero_ordem	varchar	(10),
observacao	varchar	(4000),
perc_lib_previsto	numeric	(17,2),
perc_medicao	numeric	(17,2),
qtd_medicao	numeric	(17,2),
qtd_prevista	numeric	(19,4),
responsavel	varchar	(24),
seq_comp	varchar	(10),
sld_rec_medicao	numeric	(19,4),
sld_val_medicao	numeric	(19,4),
un	varchar	(10),
usuario	varchar	(24),
val_antecip	numeric	(19,4),
val_medicao	numeric	(17,2),
val_previsto	numeric	(19,4),
val_sdo_aloc_med	numeric	(17,2)
)
