CREATE TABLE STG_ELEK_MGCAD_ITEM_CONTRAT(
acum_rec_qtd	numeric	(19,4),
acum_rec_val	numeric	(19,4),
aliquota_icm	numeric	(17,2),
aliquota_ipi	numeric	(17,2),
aliquota_iss	numeric	(17,2),
cdn_fabrican	VARCHAR(10),
char_1	varchar	(200),
char_2	varchar	(200),
check_sum	varchar	(40),
cod_comprado	varchar	(24),
cod_cond_pag	VARCHAR(10),
cod_depos	varchar	(6),
cod_emitente	VARCHAR(10),
cod_refer	varchar	(16),
codigo_icm	VARCHAR(10),
codigo_ipi	varchar	(10),
contato	varchar	(80),
dat_base	date,
dat_cotac	date,
data_1	date,
data_2	date,
dec_1	numeric	(23,8),
dec_2	numeric	(23,8),
des_referencia	varchar	(30),
ep_codigo	varchar	(6),
frequencia	VARCHAR(10),
frete	varchar	(10),
ind_caract_item	VARCHAR(10),
ind_sit_item	VARCHAR(10),
ind_tipo_control	VARCHAR(10),
ind_tipo_control_val	VARCHAR(10),
ind_un_contrato	VARCHAR(10),
int_1	VARCHAR(10),
int_2	VARCHAR(10),
it_codigo	varchar	(32),
log_1	varchar	(10),
log_2	varchar	(10),
log_control_event	varchar	(10),
log_ind_multa	varchar	(10),
log_libera	varchar	(10),
log_obrig_item	varchar	(10),
mo_codigo	VARCHAR(10),
narrat_compra	varchar	(152),
narrat_item	varchar	(4000),
nr_contrato	VARCHAR(10),
nr_dias_taxa	VARCHAR(10),
nr_tab	varchar	(20),
num_ord_inv	VARCHAR(10),
num_ord_invest	VARCHAR(10),
num_seq_item	VARCHAR(10),
ordem_base	VARCHAR(10),
perc_desconto	numeric	(17,2),
perc_multa_dia	numeric	(17,2),
perc_multa_limite	numeric	(17,2),
prazo_ent	VARCHAR(10),
pre_unit_for	numeric	(20,5),
preco_base	numeric	(25,10),
preco_fornec	numeric	(20,5),
preco_unit	numeric	(20,5),
qtd_minima	numeric	(19,4),
qtd_total	numeric	(19,4),
sld_qtd	numeric	(19,4),
sld_qtd_liber	numeric	(19,4),
sld_qtd_receb	numeric	(19,4),
sld_val	numeric	(19,4),
sld_val_liber	numeric	(19,4),
sld_val_receb	numeric	(19,4),
taxa_financ	varchar	(10),
tp_despesa	VARCHAR(10),
un	varchar	(4),
val_fatur_minimo	numeric	(19,4),
val_frete	numeric	(19,4),
val_taxa	numeric	(19,4),
val_total	numeric	(20,5),
valor_descto	numeric	(19,4)
)