"WITH ORDEM AS
(



SELECT  
TRIM(a.ixmMcu) AS FILIAL,
TRIM(A.IXKITL) AS ITEM_PAI,
        TRIM(E.IMDSC1) AS DESCRICAO_PAI,
        TRIM(E.IMSRP1) AS CLASSE,
        CASE 
		
		WHEN TRIM(E.IMSRP1) IN ('160','170','180') THEN '1'
		
		
        ELSE '1'
        END CLASSE_FI,
        A.IXTBM AS LISTA,
       --decode(instr(trim(A.IXLITM),'.'),'0',trim(A.IXLITM),substr(trim(A.IXLITM),'1',instr(trim(A.IXLITM),'.')-1)) AS ITEM_FILHO,
       
       CASE 
       WHEN trim(A.IXLITM) LIKE '%.%' THEN  TRIM(B.IMSEG1)
       ELSE trim(A.IXLITM)
        END  ITEM_FILHO,
        TRIM(B.IMDSC1) AS DESCRICAO_FILHO,
        TRIM(B.IMSRP5) AS TIPO,
         trim(G.OBEV01)||(TRIM(G.OBQ100)||' '||TRIM(OBDL011)) AS DESCRICAO_LISTA,
		case WHEN  TRIM(A.IXUOM)='TN' THEN  (A.IXBQTY/10000*1000) ELSE A.IXBQTY/10000 END  QTD_LISTA,

        TRIM(E.IMSRP1) AS CLASSE_MERCADORIA,
        TRIM(E.IMSRP2) AS SUB_CLASSE_MERCADORIA,
          SUM(CASE WHEN A.IXUM='GM' THEN (A.IXQNTY)/10000000  ELSE  DECODE(A.IXUM,B.IMUOM1,(A.IXQNTY)/10000,DECODE(C.UMCONV,0,1,(C.UMCONV/10000000)*(A.IXQNTY)/10000))     END) AS QTD
       ,B.IMUOM1 UM 
,IXDSC1


FROM    PRODDTA.F3002 A
INNER JOIN PRODDTA.F4101 B ON A.IXITM = B.IMITM
LEFT OUTER JOIN PRODDTA.F41002 C ON B.IMITM = C.UMITM AND A.IXUM = C.UMUM AND B.IMUOM1 = C.UMRUM
--INNER JOIN PRODDTA.F76411 D ON B.IMITM = ITITM
INNER JOIN PRODDTA.F4101 E ON A.IXKIT = E.IMITM
--LEFT OUTER JOIN PRODCTL.F0005 F ON TRIM(DECODE(D.ITBORI,2,1,D.ITBORI)) = TRIM(F.DRKY) AND F.DRSY = '76' AND F.DRRT = 'IO'
LEFT OUTER JOIN PRODDTA.F5503002 G ON (A.IXKIT) = (G.OBKIT) AND (A.IXTBM) = (G.OBTBM) AND (G.OBMMCU) = (A.IXMMCU)  AND TRIM(IXBQTY) = (OBBQTY)
--LEFT JOIN PRODDTA.F4102 ON IBITM=B.IMITM AND TRIM(IBMCU)=TRIM(a.ixmMcu)



--select * from proddta.f3002 where IXUM='GM'
--958040                   

WHERE /*NOT EXISTS  (SELECT 1 FROM PRODDTA.F5503002 H WHERE TRIM(H.OBEV01) IN ('N') AND TRIM(A.IXKIT) = TRIM(H.OBKIT) AND TRIM(A.IXTBM) = TRIM(H.OBTBM) AND TRIM(H.OBMMCU) = TRIM(A.IXMMCU) AND TRIM(A.IXBQTY) = TRIM(H.OBBQTY))
AND IBSTKT NOT IN ('O')
AND */suBSTR( TRIM(a.ixmMcu),1,1) IN ('1','3','6')

AND A.IXEFFT >= TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYDDD'))-1900000
AND A.IXEFFF<=TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYDDD'))-1900000
AND  G.OBEV01 = 'S'
and A.IXSBNT=0
AND TRIM(A.IXTBM) not in ('REV','REP')
--AND TRIM(a.ixmMcu)='111000'

AND EXISTS (SELECT 1 FROM  PRODDTA.F4101 H WHERE  (E.IMLITM) = (H.IMLITM)/*decode(instr(trim(H.IMLITM),'.'),'0',trim(H.IMLITM),substr(trim(H.IMLITM),'1',instr(trim(H.IMLITM),'.')-1))*/) --REMOVE EMBALAGEM
and (A.IXKITL) NOT LIKE '%.%'
GROUP BY TRIM(A.IXKITL), TRIM(E.IMDSC1), A.IXTBM,  CASE WHEN trim(A.IXLITM) LIKE '%.%' THEN  TRIM(B.IMSEG1) ELSE trim(A.IXLITM) END
        /*decode(instr(trim(A.IXLITM),'.'),'0',trim(A.IXLITM),substr(trim(A.IXLITM),'1',instr(trim(A.IXLITM),'.')-1))*/, TRIM(B.IMDSC1),TRIM(B.IMSRP5),        trim(G.OBEV01)||(TRIM(G.OBQ100)||' '||TRIM(OBDL011)) ,(case WHEN  TRIM(A.IXUOM)='TN' THEN  (A.IXBQTY/10000*1000) ELSE A.IXBQTY/10000 END),TRIM(E.IMSRP1),TRIM(a.ixmMcu)
,B.IMUOM1,TRIM(B.IMSRP1)
,  ( CASE WHEN (E.IMSRP1) IN ('160','170','180') THEN '3'       ELSE '1' END )
 ,TRIM(E.IMSRP2),IXDSC1




),SOMA AS (

SELECT 
FILIAL FILIAL_SOMA,
ITEM_PAI ITEM_PAI_SOMA,
LISTA LISTA_SOMA,
SUM(QTD) SOMA_TOTAL
FROM ORDEM
WHERE UM IN ('KG','LT')
GROUP BY FILIAL,ITEM_PAI,LISTA


), PRODUTOS_SOLIDOS AS (

SELECT
DISTINCT
trim(IMLITM) as ITEM_1,
 TRIM(IMLITM) AS ITEM,
--decode(instr(trim(IMLITM),'.'),'0',trim(IMLITM),substr(trim(IMLITM),'1',instr(trim(IMLITM),'.')-1)) AS ITEM, 
            TRIM(IMDSC1) AS DESCRICAO,
            (TRQVAL) AS ESPECIFICACAO,
            TRIM(IMSRP1) AS CLASSE,
            TRIM(TRLOTN) AS LOTE, TRIM(TRQTST) AS SOLIDOS,
            CASE 
              WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR(TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,2 ))+0.5)
              ELSE TO_NCHAR(TRIM(F3711.TRAMAX)+0.5)
            END AS SOLIDO_PRODUTO,
            CASE
              WHEN TRIM(F3711.TRAMIN) IN (NULL,'0') THEN (DECODE(TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,1 )),'C', TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,2 )),TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,1 ))))
              ELSE (TRIM(F3711.TRAMIN))
            END AS SOLIDO_PRODUTO2
    FROM PRODDTA.F3711 F3711
    LEFT OUTER JOIN PRODDTA.F4101 ON TRITM = IMITM
    WHERE (TRLOTN)='MODELO                        ' AND (TRQTST) IN ('SOLIDOS                  ') AND TRMCU='      111000'
      AND (TRIM(REGEXP_SUBSTR( UPPER((TRQVAL)),  '[^-A.]+',1,2 )) >='0' OR (F3711.TRAMAX) >='0' OR (F3711.TRAMAX) >='0')
      AND IMSRP1 NOT IN ('160','170','180','360','200','493') AND IMSRP1||IMSRP2 NOT IN ('470111','470261')
     AND IMSTKT NOT IN ('O')









UNION ALL



       SELECT  
       DISTINCT
       trim(IMLITM) as ITEM_1,
       TRIM(IMLITM) AS ITEM,
      -- decode(instr(trim(IMLITM),'.'),'0',trim(IMLITM),substr(trim(IMLITM),'1',instr(trim(IMLITM),'.')-1)) AS ITEM,
            TRIM(IMDSC1) AS DESCRICAO,
            (TRQVAL) AS ESPECIFICACAO,
            TRIM(IMSRP1) AS CLASSE,
            TRIM(TRLOTN) AS LOTE, TRIM(TRQTST) AS SOLIDOS,
            CASE 
             WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR('100')
              WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR(TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,2 )))
              ELSE TO_NCHAR(TRIM(F3711.TRAMAX))
            END AS SOLIDO_PRODUTO,

            CASE
      WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR('100')
              WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR(TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,2 )))
              ELSE TO_NCHAR(TRIM(F3711.TRAMAX))
            END AS SOLIDO_PRODUTO2

    FROM PRODDTA.F3711 F3711
    LEFT OUTER JOIN PRODDTA.F4101 ON TRITM = IMITM
    WHERE  (TRLOTN)='MODELO                        ' AND (TRQTST) IN ('SOLIDOS3                 ') AND TRMCU='      111000'
      AND IMSRP1  IN ('160','170','180','360','200','493')
      AND IMSTKT NOT IN ('O')

UNION ALL



       SELECT  
       DISTINCT
       trim(IMLITM) as ITEM_1,
       TRIM(IMLITM) AS ITEM,
      -- decode(instr(trim(IMLITM),'.'),'0',trim(IMLITM),substr(trim(IMLITM),'1',instr(trim(IMLITM),'.')-1)) AS ITEM,
            TRIM(IMDSC1) AS DESCRICAO,
            (TRQVAL) AS ESPECIFICACAO,
            TRIM(IMSRP1) AS CLASSE,
            TRIM(TRLOTN) AS LOTE, TRIM(TRQTST) AS SOLIDOS,
            CASE 
             WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR('100')
              WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR(TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,2 )))
              ELSE TO_NCHAR(TRIM(F3711.TRAMAX))
            END AS SOLIDO_PRODUTO,

            CASE
      WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR('100')
              WHEN TRIM(F3711.TRAMAX) IN (NULL,'0') THEN TO_NCHAR(TRIM(REGEXP_SUBSTR( UPPER(TRQVAL),  '[^-A.]+',1,2 )))
              ELSE TO_NCHAR(TRIM(F3711.TRAMAX))
            END AS SOLIDO_PRODUTO2

    FROM PRODDTA.F3711 F3711
    LEFT OUTER JOIN PRODDTA.F4101 ON TRITM = IMITM
    WHERE  (TRLOTN)='MODELO                        ' AND (TRQTST) IN ('SOLIDOS3                 ') AND TRMCU='      111000'
       AND IMSRP1  IN ('470','140') and imsrp2 IN ('261','279','280','281','283')
      AND IMSTKT NOT IN ('O')





), ORDEM2 AS (  --SE  TIVER NAS CLASSES ('140','160','170','180') PEGA QTD SECO DA LISTA, CASO CONTRARIO, QTD CONVERTIDO *100





    SELECT 
    A.UM,
    A.CLASSE_FI,
    A.FILIAL,
    a.CLASSE CLASSE,
    A.ITEM_PAI ,
          A.DESCRICAO_PAI,
          A.LISTA,
          A.ITEM_FILHO,
          A.DESCRICAO_FILHO,
          A.TIPO,
          A.QTD,
          A.DESCRICAO_LISTA,
          A.CLASSE_MERCADORIA,
          A.SUB_CLASSE_MERCADORIA,
          --ALTERADO DIA 30/09/2016 PARA INSERIR CALCULO DIFERENTE PARA POLIESTER
        /*  CASE 
            WHEN CLASSE_MERCADORIA IN ('140','160','170','180') THEN  QTD_LISTA
            --WHEN CLASSE_MERCADORIA IN ('180') THEN  QTD_LISTA
            ELSE (SELECT SUM(B.QTD) FROM ORDEM B WHERE A.ITEM_PAI = B.ITEM_PAI AND A.LISTA = B.LISTA)*100 */
            CASE 
				WHEN CLASSE_MERCADORIA='180' AND SUB_CLASSE_MERCADORIA in ('278')  THEN 1
            WHEN CLASSE_MERCADORIA='360' AND SUB_CLASSE_MERCADORIA in ('220','136') AND SOMA_TOTAL<2 AND SOMA_TOTAL>0.8 THEN 1

          when QTD_LISTA>0  and CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  then QTD_LISTA
               WHEN CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  AND SOMA_TOTAL<1.30 AND SOMA_TOTAL>0.8 THEN  1
             WHEN CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  AND SOMA_TOTAL<1200 AND SOMA_TOTAL>900 THEN  1000
			        WHEN CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  AND SOMA_TOTAL<9300 AND SOMA_TOTAL>8700 THEN  9000
					       WHEN CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  AND SOMA_TOTAL<8300 AND SOMA_TOTAL>7700 THEN  8000
						          WHEN CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  AND SOMA_TOTAL<120 AND SOMA_TOTAL>90 THEN  100
             WHEN CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  AND SOMA_TOTAL<14200 AND SOMA_TOTAL>13800 THEN  14000
                WHEN CLASSE_MERCADORIA IN ('170','160','180','360','200','493')  AND SOMA_TOTAL<1850 AND SOMA_TOTAL>1750 THEN  1800


			             when QTD_LISTA>0  and CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283') then QTD_LISTA
               WHEN CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283')   AND SOMA_TOTAL<1.30 AND SOMA_TOTAL>0.8 THEN  1
             WHEN CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283')    AND SOMA_TOTAL<1200 AND SOMA_TOTAL>900 THEN  1000
			        WHEN CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283')  AND SOMA_TOTAL<9300 AND SOMA_TOTAL>8700 THEN  9000
					       WHEN CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283')    AND SOMA_TOTAL<8300 AND SOMA_TOTAL>7700 THEN  8000
						          WHEN CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283')    AND SOMA_TOTAL<120 AND SOMA_TOTAL>90 THEN  100
             WHEN CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283')    AND SOMA_TOTAL<14200 AND SOMA_TOTAL>13800 THEN  14000
                WHEN CLASSE_MERCADORIA IN ('470','140')  AND SUB_CLASSE_MERCADORIA in ('261','279','280','281','283')   AND SOMA_TOTAL<1850 AND SOMA_TOTAL>1750 THEN  1800






            --WHEN CLASSE_MERCADORIA IN ('180') THEN  QTD_LISTA
            ELSE (SELECT SUM(B.QTD) FROM ORDEM B WHERE A.ITEM_PAI = B.ITEM_PAI AND A.LISTA = B.LISTA  AND A.FILIAL=B.FILIAL )*100

          END SOMA
    FROM ORDEM A
    LEFT JOIN SOMA ON A.FILIAL=FILIAL_SOMA AND A.ITEM_PAI=ITEM_PAI_SOMA AND A.LISTA=LISTA_SOMA 






), SOLIDO_PRODUTO_T AS (




SELECT  DISTINCT 
trim(IMLITM) ITEM_1,
TRIM(IMLITM) AS ITEM,
--decode(instr(trim(IMLITM),'.'),'0',trim(IMLITM),substr(trim(IMLITM),'1',instr(trim(IMLITM),'.')-1)) AS ITEM,
        TRIM(IMDSC1) AS DESCRICAO,
        TO_NCHAR(' ') AS ESPECIFICACAO,
        TRIM(IMSRP1) AS CLASSE,

        CASE 
          WHEN IMSRP1 IN ('180') THEN TO_NCHAR(100.5)-- SE FOR POLIENTES 

         ELSE TO_NCHAR(100.5) 
        END SOLIDO_PRODUTO,            

        TO_NCHAR(100) AS SOLIDO_PRODUTO2
FROM  PRODDTA.F4101 

   WHERE IMPRP1  IN ('160','170','180','360','200','493') 
    AND  /* decode(instr(trim(IMLITM),'.'),'0',trim(IMLITM),substr(trim(IMLITM),'1',instr(trim(IMLITM),'.')-1))*/ trim(IMLITM) NOT IN  (SELECT TRIM(ITEM) FROM PRODUTOS_SOLIDOS)
    AND IMSTKT NOT IN ('O')

    --SE FOR SOLIDO



UNION ALL

SELECT  DISTINCT 
trim(IMLITM) ITEM_1,
TRIM(IMLITM) AS ITEM,
--decode(instr(trim(IMLITM),'.'),'0',trim(IMLITM),substr(trim(IMLITM),'1',instr(trim(IMLITM),'.')-1)) AS ITEM,
        TRIM(IMDSC1) AS DESCRICAO,
        TO_NCHAR(' ') AS ESPECIFICACAO,
        TRIM(IMSRP1) AS CLASSE,

        CASE 
          WHEN IMSRP1 IN ('180') THEN TO_NCHAR(100.5)-- SE FOR POLIENTES 

         ELSE TO_NCHAR(100.5) 
        END SOLIDO_PRODUTO,            

        TO_NCHAR(100) AS SOLIDO_PRODUTO2
FROM  PRODDTA.F4101 

WHERE IMPRP1  IN ('470','140')  AND IMPRP2 in ('261','279','280','281','283')
    AND  /* decode(instr(trim(IMLITM),'.'),'0',trim(IMLITM),substr(trim(IMLITM),'1',instr(trim(IMLITM),'.')-1))*/ trim(IMLITM) NOT IN  (SELECT TRIM(ITEM) FROM PRODUTOS_SOLIDOS)
    AND IMSTKT NOT IN ('O')

    --SE FOR SOLIDO






),SOLIDO_PRODUTO AS (


SELECT ITEM_1,TO_NCHAR(ITEM) AS ITEM, TO_NCHAR(DESCRICAO) AS DESCRICAO, TO_NCHAR(ESPECIFICACAO) AS ESPECIFICACAO, TO_NCHAR(CLASSE) AS  CLASSE_MERCADORIA, 
  TO_NCHAR(SOLIDO_PRODUTO) AS SOLIDO_PRODUTO, 
  (SOLIDO_PRODUTO2 + SOLIDO_PRODUTO)/2 AS SOLIDO_PRODUTO2
  FROM SOLIDO_PRODUTO_T


UNION ALL

  SELECT ITEM_1,TO_NCHAR(ITEM) AS ITEM, TO_NCHAR(DESCRICAO) AS DESCRICAO, TO_NCHAR(ESPECIFICACAO) AS ESPECIFICACAO, TO_NCHAR(CLASSE) AS  CLASSE_MERCADORIA, 
  TO_NCHAR(SOLIDO_PRODUTO) AS SOLIDO_PRODUTO, 
  (SOLIDO_PRODUTO2 + SOLIDO_PRODUTO)/2 AS SOLIDO_PRODUTO2
  FROM PRODUTOS_SOLIDOS




),ORDEM3 AS (

  SELECT  
  UM,
  CLASSE,
  CLASSE_FI,
  C.ITEM_1,
  FILIAL,
  ITEM_PAI, 
            DESCRICAO_PAI, 
            LISTA, 
            ITEM_FILHO, 
            DESCRICAO_FILHO,
            TIPO, 
            QTD,
           DESCRICAO_LISTA,

		   CASE 
		   WHEN CLASSE ='450'  AND A.ITEM_FILHO!='AGUA' THEN 1
            ELSE 
			DECODE(A.ITEM_FILHO,'AGUA',0,'USO',0,NVL2(C.SOLIDO_PRODUTO2, C.SOLIDO_PRODUTO2/100,B.IMSTDP/100000)) END  FRAC_SOL,

            CASE 
		   WHEN CLASSE ='450'  AND A.ITEM_FILHO!='AGUA' THEN QTD*1
            ELSE 
			QTD*DECODE(A.ITEM_FILHO,'AGUA',0,'USO',0,NVL2(C.SOLIDO_PRODUTO2, C.SOLIDO_PRODUTO2/100,B.IMSTDP/100000)) END  SOLIDO_TEORICO,




            A.SOMA,
            A.CLASSE_MERCADORIA,
			A.SUB_CLASSE_MERCADORIA
        ,C.SOLIDO_PRODUTO
        ,C.SOLIDO_PRODUTO2

    FROM ORDEM2 A
    LEFT OUTER JOIN PRODDTA.F4101 B ON TRIM(A.ITEM_FILHO)=TRIM(B.IMLITM)-- decode(instr(trim(A.ITEM_FILHO),'.'),'0',trim(A.ITEM_FILHO),substr(trim(A.ITEM_FILHO),'1',instr(trim(A.ITEM_FILHO),'.')-1)) = TRIM(B.IMLITM)
    LEFT OUTER JOIN SOLIDO_PRODUTO C  ON trim(A.ITEM_FILHO)=trim( C.ITEM)  
	WHERE DECODE(SOMA,0,0,NULL,0,QTD/SOMA*10000) >'0'









),V_CUSTO_MP AS (



SELECT 
DISTINCT



TRIM(IBMCU) AS FILIAL_ITEM,
CASE WHEN IMLITM LIKE 'AES%' THEN TRIM (IMLITM)
ELSE 
TRIM(IMLITM) END COD_ITEM,
TRIM(IMDSC1)||' '||TRIM(IMDSC2) DSC,

A.COUNCS/10000  CUSTO_PADRAO,

CASE 
WHEN  TRIM(IMLITM) IN ('970214') THEN  PA.COUNCS/10000
WHEN  USD.COUNCS IS NOT NULL THEN  ROUND((USD.COUNCS/10000)*NVL((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)) ,1),6)
WHEN  EUR.COUNCS IS NOT NULL THEN  ROUND((EUR.COUNCS/10000)*NVL((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='EUR' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)) ,1),6)
WHEN  BRL.COUNCS IS NOT NULL THEN  BRL.COUNCS/10000
else 0
--ELSE  A.COUNCS/10000

END CUSTO_MOEDA_LOCAL


FROM proddta.f4101
LEFT JOIN PRODDTA.F4102 ON IMITM=IBITM
LEFT JOIN PRODDTA.F4105 A ON  (A.COLITM)=(IBLITM)  AND (IBMCU)=(A.COMCU) AND (A.COCSIN)='I' --PADRAO
LEFT JOIN PRODDTA.F4105 USD ON USD.COITM=A.COITM AND USD.COMCU=A.COMCU AND USD.COLEDG='41' 
LEFT JOIN PRODDTA.F4105 EUR ON EUR.COITM=A.COITM AND EUR.COMCU=A.COMCU AND EUR.COLEDG='42' 
LEFT JOIN PRODDTA.F4105 BRL ON BRL.COITM=A.COITM AND BRL.COMCU=A.COMCU AND BRL.COLEDG='43'
LEFT JOIN PRODDTA.F4105 PA ON PA.COITM=A.COITM AND PA.COMCU=A.COMCU AND PA.COLEDG='44' 
WHERE  A.COUNCS IS NOT NULL
and (IBMCU) IN ('      111000') 




), ORDEM4 AS (

SELECT   

a.FRAC_SOL,
A.UM,
A.CLASSE,
a.CLASSE_FI,
A.FILIAL,
A.ITEM_PAI, 
        A.DESCRICAO_PAI, 
        A.LISTA, 
        A.ITEM_FILHO, 
        A.DESCRICAO_FILHO, 
        A.TIPO,
        A.QTD,
        A.SOMA,
        A.DESCRICAO_LISTA,
        A.CLASSE_MERCADORIA,
        A.SUB_CLASSE_MERCADORIA,
        CASE
          --WHEN A.CLASSE_MERCADORIA IN ('180') THEN A.SOMA
           WHEN TRIM(A.CLASSE_MERCADORIA) IN ('160','170','180','360','200','493') THEN A.SOMA
		  WHEN TRIM(A.CLASSE_MERCADORIA) IN ('470')  AND TRIM(A.SUB_CLASSE_MERCADORIA) in ('261','279','280','281','283') THEN A.SOMA

          ELSE (SELECT SUM(ORDEM3.SOLIDO_TEORICO) FROM ORDEM3 WHERE A.ITEM_PAI = ORDEM3.ITEM_PAI AND A.LISTA = ORDEM3.LISTA   AND A.FILIAL=ORDEM3.FILIAL ) 
        END SOLIDO_TEORICO,

        B.SOLIDO_PRODUTO AS SOLIDO_PRODUTO,
        B.SOLIDO_PRODUTO2,
        NVL2(C.CUSTO_MOEDA_LOCAL,C.CUSTO_MOEDA_LOCAL,'0') AS CUSTO_TOTAL ,
        NVL(SERV.COUNCS/10000,0) AS CUSTO_SERV,
 NVL(MATE.COUNCS/10000,0) AS CUSTO_MATE

FROM ORDEM3 A
INNER JOIN SOLIDO_PRODUTO B ON (A.ITEM_PAI)=(B.ITEM_1) --decode(instr(trim(A.ITEM_PAI),'.'),'0',trim(A.ITEM_PAI),substr(trim(A.ITEM_PAI),'1',instr(trim(A.ITEM_PAI),'.')-1)) = trim(B.ITEM_1)   
LEFT OUTER JOIN V_CUSTO_MP C ON (A.ITEM_FILHO) = (C.COD_ITEM) AND SUBSTR(FILIAL_ITEM,1,1)=substr(CLASSE_FI,1,1)
LEFT JOIN PRODDTA.F4105 SERV ON TRIM(SERV.COLITM)=(A.ITEM_PAI) AND TRIM(SERV.COMCU)='111000' AND SERV.COLEDG='44' 

LEFT JOIN PRODDTA.F4105 MATE ON TRIM(MATE.COLITM)=(A.ITEM_PAI) AND TRIM(MATE.COMCU)='111000' AND MATE.COLEDG='40' 









), ORDEM5_TEMP AS (

SELECT 
a.SOLIDO_PRODUTO,
a.FRAC_SOL,
A.UM,
A.CLASSE,
A.FILIAL,
A.ITEM_PAI,
        A.DESCRICAO_PAI, 
        A.LISTA, 
        A.ITEM_FILHO, 
        A.DESCRICAO_FILHO,
        A.QTD AS QTDE_LIMPA, 
        A.SOMA AS SOMA,
        A.SOLIDO_TEORICO,

        A.TIPO,
        A.DESCRICAO_LISTA,
        --ALTERAÇÃO DIA 26/06/2018 CALCULO PELO RENDIMENTO FINAL DO PRODUTO
        CASE WHEN  A.CLASSE_MERCADORIA IN ('160','170','180','360','200','493') THEN A.QTD/A.SOMA
		WHEN  A.CLASSE_MERCADORIA IN ('470') AND A.SUB_CLASSE_MERCADORIA in ('261','279','280','281','283') THEN A.QTD/A.SOMA
       ELSE A.QTD/(A.SOLIDO_TEORICO/ A.SOLIDO_PRODUTO)/100 END AS QTD,

        A.CUSTO_TOTAL,
        --ALTERAÇÃO PARA O CALCULO DO PRODUTO 
        CASE 
        WHEN  A.CLASSE_MERCADORIA IN ('160','170','180','360','200','493') THEN A.QTD/A.SOMA * A.CUSTO_TOTAL
		WHEN  A.CLASSE_MERCADORIA IN ('470') AND A.SUB_CLASSE_MERCADORIA in ('261','279','280','281','283') THEN A.QTD/A.SOMA * A.CUSTO_TOTAL
        ELSE A.QTD  /((A.SOLIDO_TEORICO/ A.SOLIDO_PRODUTO)/100) * A.CUSTO_TOTAL 
        END AS CUSTO_UNITARIO,
        A.CUSTO_SERV,
		        A.CUSTO_MATE,
A.CLASSE_MERCADORIA,
A.SUB_CLASSE_MERCADORIA

FROM ORDEM4 A
WHERE A.SOLIDO_TEORICO >'0'
--AND  ITEM_PAI='148326'

), ORDEM5_SOMA AS (
SELECT 
SUM(QTD) QTD_SOMA_5,
count(QTD) QTD_VEZES,
ITEM_PAI AS ITEM_PAI5,
LISTA AS LISTA_5,
FILIAL AS FILIAL_5
FROM ORDEM5_TEMP

GROUP BY ITEM_PAI,LISTA,FILIAL

), ORDEM5 AS (

--MULTIPLICA PARA VIRAR 1KG
SELECT 
QTD_VEZES,
SOLIDO_PRODUTO,
FRAC_SOL,
UM,
CLASSE,
SUB_CLASSE_MERCADORIA,
FILIAL,
ITEM_PAI,
DESCRICAO_PAI,
LISTA,
ITEM_FILHO,
DESCRICAO_FILHO,
QTDE_LIMPA,
SOMA,
SOLIDO_TEORICO,

TIPO,
DESCRICAO_LISTA,
CASE 
WHEN CLASSE IN ('180')  THEN ROUND(QTDE_LIMPA/SOMA,6)
ELSE QTD
END QTD,
ROUND(CUSTO_TOTAL,6) CUSTO_TOTAL,
CASE 
WHEN CLASSE IN ('180') THEN ROUND( (CUSTO_TOTAL*(QTDE_LIMPA/SOMA)),6) 
ELSE ROUND(CUSTO_UNITARIO,6) 
END CUSTO_UNITARIO,
CUSTO_SERV,
CUSTO_MATE

FROM ORDEM5_TEMP
INNER JOIN ORDEM5_SOMA ON ITEM_PAI=ITEM_PAI5 AND   LISTA=LISTA_5 AND FILIAL_5=FILIAL





),LISTA_ATIVA1 as (

    --ITENS QUE SÓ TEM UMA LISTA ATIVA, NESTE CASO SOMENTE TRAGO ELA--
  select distinct B.IMLITM AS ITEM, case when A.OBTBM='PM' then 'M' else to_char(A.OBTBM) end   LISTA
  FROM PRODDTA.F5503002 A
  INNER JOIN PRODDTA.F4101  B ON (B.IMITM) = (A.OBKIT)
  WHERE A.OBEV01 = 'S'
  AND NOT EXISTS (SELECT 1 FROM PRODDTA.F5503002 B WHERE A.OBKIT = B.OBKIT AND A.OBTBM != B.OBTBM AND OBEV01 = 'S' and EXISTS (SELECT 1 FROM  proddta.f3002 where ixkit=obkit and obmmcu=ixmmcu and obtbm=ixtbm AND IXBQTY=OBBQTY))
    and EXISTS (SELECT 1 FROM  proddta.f3002 where ixkit=obkit and obmmcu=ixmmcu and obtbm=ixtbm  AND IXBQTY=OBBQTY)


  UNION ALL

  --\/ data de produção
  --ITENS QUE TEM MAIS DE UMA LISTA ATIVA. NESTE CASO PRECISO BUSCAR A ÚLTIMA ORDEM DE PRODUÇÃO PARA SABER QUAL FOI O ÚLTIMO PRODUZIDO--
  select distinct D.IMLITM AS ITEM, case when A.OBTBM='PM' then 'M' else to_char(A.OBTBM) end   LISTA
  FROM PRODDTA.F5503002 A  
  INNER JOIN PRODDTA.F4801   C ON A.OBTBM = C.WATBM AND  A.OBKIT = C.WAITM
  INNER JOIN PRODDTA.F4101  D ON (D.IMITM) = (A.OBKIT)
  WHERE A.OBEV01 = 'S'
  and (WATBM) NOT IN ('REP','REV')
  AND  EXISTS (SELECT 1 FROM PRODDTA.F5503002 B WHERE A.OBKIT = B.OBKIT AND A.OBTBM != B.OBTBM AND OBEV01 = 'S' and EXISTS (SELECT 1 FROM  proddta.f3002 where ixkit=obkit and obmmcu=ixmmcu and obtbm=ixtbm AND IXBQTY=OBBQTY))
  AND c.watrdj||c.WADOCO IN (SELECT MAX(D.watrdj||D.WADOCO) FROM PRODDTA.F4801 D WHERE C.WAITM = D.WAITM  AND (D.WATBM) NOT IN ('REV','REP') )
    and EXISTS (SELECT 1 FROM  proddta.f3002 where ixkit=obkit and obmmcu=ixmmcu and obtbm=ixtbm  AND IXBQTY=OBBQTY)







), LISTA_ATIVA2 AS(

    --CASO NÃO SEJA NEM UM NEM O OUTRO, BUSCAR O QUE FOI MODIFICADO POR ÚLTIMO
    SELECT DISTINCT  D.IMLITM AS ITEM, 'M' AS LISTA --A.OBTBM AS LISTA 
    FROM PRODDTA.F5503002 A
    INNER JOIN PRODDTA.F4101  D ON (D.IMITM) = (A.OBKIT)
    WHERE 
    D.IMLITM NOT IN (SELECT ITEM FROM LISTA_ATIVA1)
    AND OBEV01 = 'S'
     and EXISTS (SELECT 1 FROM  proddta.f3002 where ixkit=obkit and obmmcu=ixmmcu and obtbm=ixtbm  AND IXBQTY=OBBQTY)
    AND OBUPMJ||LPAD(OBUPMT,6,0) = (SELECT MAX(OBUPMJ||LPAD(OBUPMT,6,0)) FROM PRODDTA.F5503002 B WHERE A.OBKIT =B.OBKIT AND B.OBEV01 = 'S')



), LISTA_ATIVA3 AS(

    --CASO NÃO SEJA NEM UM NEM O OUTRO, e não tem registro na obs de lista de material

    SELECT DISTINCT  D.IMLITM AS ITEM, 'M' AS LISTA 
    FROM PRODDTA.F4101  D
    WHERE 
    D.IMLITM NOT IN (SELECT ITEM FROM LISTA_ATIVA2)
   and D.IMLITM NOT IN (SELECT ITEM FROM LISTA_ATIVA1)

), LISTA_ATIVA_ULTIMA AS(

  SELECT ITEM ,to_char(LISTA) LISTA FROM LISTA_ATIVA1 

  UNION ALL
  SELECT ITEM ,to_char(LISTA) LISTA FROM LISTA_ATIVA2
    UNION ALL
  SELECT ITEM ,to_char(LISTA) LISTA FROM LISTA_ATIVA3






 ),DATA_PRODUCAO AS (

    SELECT DISTINCT A.OBKIT AS ITEM, A.OBTBM AS LISTA, C.WATRDJ AS DATA
  FROM PRODDTA.F5503002 A  
  INNER JOIN PRODDTA.F4801 C ON (A.OBTBM) = (C.WATBM) AND  A.OBKIT = C.WAITM
  WHERE C.WATRDJ IN (SELECT MAX(D.WATRDJ) FROM PRODDTA.F4801 D WHERE C.WAITM = D.WAITM AND C.WATBM = D.WATBM AND ROWNUM = '1'  AND TRIM(D.WATBM) NOT IN ('REV','REP'))
    and EXISTS (SELECT 1 FROM  proddta.f3002 where ixkit=obkit and obmmcu=ixmmcu and obtbm=ixtbm  AND IXBQTY=OBBQTY)
 AND (WATBM) NOT IN ('REV','REP')



),LISTA_FILIAL1 AS (
-- SE HOUVER FILIAL E MATROZ COM A MESMA LISTA, PROCURA A FILIAL
  SELECT 
  DISTINCT 
  TRIM(IXKITL) AS PAIL,
  TRIM(IXTBM) AS LISTAL,
  TRIM(IXMMCU) AS FILIALL

  FROM PRODDTA.F3002 A
  LEFT JOIN PRODDTA.F4102 ON IBITM=IXKIT AND TRIM(IBMCU)=TRIM(ixmMcu)
  inner join proddta.f4101 ON IMITM=IXKIT
  INNER   JOIN PRODDTA.F5503002 G ON (A.IXKIT) = (G.OBKIT) AND (A.IXTBM) = (G.OBTBM) AND (G.OBMMCU) = (A.IXMMCU) AND (IXBQTY) = (OBBQTY)   AND OBEV01 = 'S'

WHERE IBSTKT NOT IN ('O')
AND suBSTR( TRIM(ixmMcu),1,1) IN ('1','3','6')

AND IXEFFT >= TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYDDD'))-1900000
AND IXEFFF<=TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYDDD'))-1900000
AND TRIM(TRIM(IXTBM)) IN (SELECT TRIM(LISTA)  FROM LISTA_ATIVA_ULTIMA WHERE TRIM(IXKITL) = TRIM(ITEM)) --LISTA ATIVA
and trim( IXTBM) not in ('REV','REP')
--AND TRIM(IXKITL)='73462'

),LISTA_FILIAL2 AS (
-- pega a filial 111005 menos a 311002
select PAIL,LISTAL,case when FILIALL='311002' then '311000' else to_char(FILIALL) end FILIALL from (
select 
PAIL PAIL,
LISTAL LISTAL,
max(FILIALL) FILIALL

FROM LISTA_FILIAL1
group by PAIL,LISTAL
)






),V_LISTA4 as (
SELECT
A.CLASSE AS CLASSE,
A.FILIAL AS FILIAL,
B.FILIAL AS FILIALB,
C.FILIAL AS FILIALC,
G.FILIAL AS FILIALG,
H.FILIAL AS FILIALH,
A.ITEM_PAI AS ITEM_PAI,
        A.DESCRICAO_PAI AS DESCRICAO_PAI,
        TO_CHAR(F.IMPRP1) AS CLASS_ITEM,
        A.LISTA AS LISTA,
        B.LISTA AS LISTAB,
        C.LISTA AS LISTAC,
        A.QTD AS QTD,

            CASE 




		WHEN G.QTD IS NOT NULL AND G.SUB_CLASSE_MERCADORIA IN ('278') AND  G.CLASSE IN ('180')  THEN (round( G.QTD * G.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='40' AND G.ITEM_PAI=TRIM(COLITM))/G.QTD_VEZES)   
         WHEN C.QTD IS NOT NULL AND C.SUB_CLASSE_MERCADORIA IN ('278') AND  C.CLASSE IN ('180')   THEN (round( C.QTD * C.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='40' AND C.ITEM_PAI=TRIM(COLITM))/c.QTD_VEZES)   
          WHEN B.QTD IS NOT NULL AND B.SUB_CLASSE_MERCADORIA IN ('278') AND  B.CLASSE IN ('180')  THEN (round( B.QTD * B.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='40' AND B.ITEM_PAI=TRIM(COLITM))/B.QTD_VEZES)  

		WHEN G.QTD IS NOT NULL AND G.CLASSE IN ('470')  THEN (round( G.QTD * G.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND G.ITEM_PAI=TRIM(COLITM))/G.QTD_VEZES)   
         WHEN C.QTD IS NOT NULL AND C.CLASSE IN ('470') THEN (round( C.QTD * C.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND C.ITEM_PAI=TRIM(COLITM))/c.QTD_VEZES)   
          WHEN B.QTD IS NOT NULL AND B.CLASSE IN ('470') THEN (round( B.QTD * B.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND B.ITEM_PAI=TRIM(COLITM))/B.QTD_VEZES)   



         WHEN G.QTD IS NOT NULL AND G.ITEM_PAI IN ('970214')  THEN (round( G.QTD * G.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND G.ITEM_PAI=TRIM(COLITM))/G.QTD_VEZES)   
         WHEN C.QTD IS NOT NULL AND C.ITEM_PAI IN ('970214')  THEN (round( C.QTD * C.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND C.ITEM_PAI=TRIM(COLITM))/c.QTD_VEZES)   
          WHEN B.QTD IS NOT NULL AND B.ITEM_PAI IN ('970214')  THEN (round( B.QTD * B.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND B.ITEM_PAI=TRIM(COLITM))/B.QTD_VEZES)   
           WHEN A.QTD IS NOT NULL AND A.ITEM_PAI IN ('970214' )  THEN A.CUSTO_TOTAL

             WHEN H.CUSTO_TOTAL IS NOT NULL THEN H.CUSTO_TOTAL
              WHEN G.CUSTO_TOTAL IS NOT NULL THEN G.CUSTO_TOTAL
         WHEN C.CUSTO_TOTAL IS NOT NULL THEN C.CUSTO_TOTAL
         WHEN B.CUSTO_TOTAL IS NOT NULL THEN B.CUSTO_TOTAL
     WHEN A.CUSTO_TOTAL IS NOT NULL THEN A.CUSTO_TOTAL
          END  CUSTO_TOTAL,


        A.CUSTO_SERV AS CUSTO_SERV,
		A.CUSTO_MATE AS CUSTO_MATE,
        A.TIPO AS TIPO,
        A.DESCRICAO_LISTA AS DESCRICAO_LISTA,
        TRIM(F.IMSRP0) AS TABELA_CELULA,
        CASE
          WHEN C.QTD IS NOT NULL THEN '3'
          WHEN B.QTD IS NOT NULL THEN '2'
          ELSE '1' END  NIVEL,
        A.ITEM_FILHO AS ITEM_FILHO1,
        A.DESCRICAO_FILHO AS DESCRICAO_FILHO1,
        B.ITEM_FILHO AS ITEM_FILHO2,
        B.DESCRICAO_FILHO AS DESCRICAO_FILHO2,
        C.ITEM_FILHO AS ITEM_FILHO3,
        C.DESCRICAO_FILHO AS DESCRICAO_FILHO3,
        A.QTD AS QTD1,
        B.QTD AS QTD2,
        C.QTD AS QTD3,


        CASE 

		WHEN G.QTD IS NOT NULL AND G.SUB_CLASSE_MERCADORIA IN ('278') AND  G.CLASSE IN ('180')  THEN A.QTD * B.QTD*G.QTD *  (round( G.QTD * G.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='40' AND G.ITEM_PAI=TRIM(COLITM))/G.QTD_VEZES)   
        WHEN C.QTD IS NOT NULL AND C.SUB_CLASSE_MERCADORIA IN ('278') AND  C.CLASSE IN ('180')  THEN A.QTD * B.QTD  *(round( C.QTD * C.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='40' AND C.ITEM_PAI=TRIM(COLITM))/C.QTD_VEZES)   
        WHEN B.QTD IS NOT NULL AND B.SUB_CLASSE_MERCADORIA IN ('278') AND  B.CLASSE IN ('180')  THEN A.QTD *  (round( B.QTD * B.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='40' AND B.ITEM_PAI=TRIM(COLITM))/B.QTD_VEZES)   

		    WHEN G.QTD IS NOT NULL AND G.CLASSE IN ('470')  THEN A.QTD * B.QTD*G.QTD *  (round( G.QTD * G.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND G.ITEM_PAI=TRIM(COLITM))/G.QTD_VEZES)   
         WHEN C.QTD IS NOT NULL AND C.CLASSE IN ('470')  THEN A.QTD * B.QTD  *(round( C.QTD * C.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND C.ITEM_PAI=TRIM(COLITM))/C.QTD_VEZES)   
          WHEN B.QTD IS NOT NULL AND B.CLASSE IN ('470')  THEN A.QTD *  (round( B.QTD * B.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND B.ITEM_PAI=TRIM(COLITM))/B.QTD_VEZES)   



         WHEN G.QTD IS NOT NULL AND G.ITEM_PAI IN ('970214')  THEN A.QTD * B.QTD*G.QTD *  (round( G.QTD * G.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND G.ITEM_PAI=TRIM(COLITM))/G.QTD_VEZES)   
         WHEN C.QTD IS NOT NULL AND C.ITEM_PAI IN ('970214' )  THEN A.QTD * B.QTD  *(round( C.QTD * C.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND C.ITEM_PAI=TRIM(COLITM))/C.QTD_VEZES)   
          WHEN B.QTD IS NOT NULL AND B.ITEM_PAI IN ('970214')  THEN A.QTD *  (round( B.QTD * B.CUSTO_TOTAL,6)+ (SELECT COUNCS/10000 FROM PRODDTA.F4105 WHERE COLEDG='44' AND B.ITEM_PAI=TRIM(COLITM))/B.QTD_VEZES)   
      WHEN A.QTD IS NOT NULL AND A.ITEM_PAI IN ('970214')  THEN round(A.QTD* A.CUSTO_TOTAL,6)


         WHEN H.QTD IS NOT NULL THEN round(A.QTD * B.QTD * C.QTD * G.QTD * H.QTD * H.CUSTO_TOTAL,6) --NIVEL5
          WHEN G.QTD IS NOT NULL THEN round(A.QTD * B.QTD * C.QTD * G.QTD * G.CUSTO_TOTAL,6) --NIVEL4
          WHEN C.QTD IS NOT NULL THEN round(A.QTD * B.QTD * C.QTD * C.CUSTO_TOTAL,6) --NIVEL3
          WHEN B.QTD IS NOT NULL THEN round( A.QTD * B.QTD * B.CUSTO_TOTAL,6) --NIVEL2
          ELSE round(A.QTD* A.CUSTO_TOTAL,6) --NIVEL1
        END CUSTO_UNITARIO,



        NVL2(D.LISTA,'S','N') AS ULT_PRODUZIDA,
        E.DATA AS DATA_ULT_PRODUCAO
FROM ORDEM5 A
LEFT OUTER JOIN ORDEM5 B ON A.TIPO = 'PA' AND TRIM(B.LISTA) IN (SELECT CASE WHEN TRIM(LISTA)='REP' THEN 'M' ELSE TO_CHAR(TRIM(LISTA)) END  FROM LISTA_ATIVA_ULTIMA WHERE B.ITEM_PAI = TRIM(ITEM)) AND A.ITEM_FILHO = B.ITEM_PAI AND TRIM(A.FILIAL)=(CASE WHEN A.ITEM_FILHO LIKE 'RD%' AND A.FILIAL = '111000' THEN '111000' WHEN TRIM(A.FILIAL)='111005' THEN  '111005'  WHEN TRIM(A.FILIAL)='111002' THEN  '111002'  ELSE  TO_CHAR((REPLACE(TRIM(B.FILIAL),'111005','111000')))  END ) --AND TRIM(B.FILIAL) IN (CASE WHEN B.ITEM_FILHO LIKE 'RD%' THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE B.ITEM_PAI=PAIL AND TRIM(B.LISTA)=LISTAL )END  ) 
LEFT OUTER JOIN ORDEM5 C ON B.TIPO = 'PA' AND TRIM(C.LISTA) IN (SELECT CASE WHEN TRIM(LISTA)='REP' THEN 'M' ELSE TO_CHAR(TRIM(LISTA)) END  FROM LISTA_ATIVA_ULTIMA WHERE C.ITEM_PAI = TRIM(ITEM)) AND B.ITEM_FILHO = C.ITEM_PAI AND TRIM(B.FILIAL)=(CASE WHEN B.ITEM_FILHO LIKE 'RD%' AND B.FILIAL = '111000' THEN '111000' WHEN TRIM(B.FILIAL)='111005' THEN  '111005'  WHEN TRIM(B.FILIAL)='111002' THEN  '111002'  ELSE  TO_CHAR((REPLACE(TRIM(C.FILIAL),'111005','111000')))  END ) --AND TRIM(C.FILIAL) IN (CASE WHEN C.ITEM_FILHO LIKE 'RD%' THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE C.ITEM_PAI=PAIL AND TRIM(C.LISTA)=LISTAL )END  ) 
LEFT OUTER JOIN ORDEM5 G ON C.TIPO = 'PA' AND TRIM(G.LISTA) IN (SELECT CASE WHEN TRIM(LISTA)='REP' THEN 'M' ELSE TO_CHAR(TRIM(LISTA)) END  FROM LISTA_ATIVA_ULTIMA WHERE G.ITEM_PAI = TRIM(ITEM)) AND C.ITEM_FILHO = G.ITEM_PAI AND TRIM(C.FILIAL)=(CASE WHEN C.ITEM_FILHO LIKE 'RD%' AND C.FILIAL = '111000' THEN '111000' WHEN TRIM(C.FILIAL)='111005' THEN  '111005'  WHEN TRIM(C.FILIAL)='111002' THEN  '111002'  ELSE  TO_CHAR((REPLACE(TRIM(G.FILIAL),'111005','111000')))  END ) --AND TRIM(G.FILIAL) IN (CASE WHEN G.ITEM_FILHO LIKE 'RD%' THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE G.ITEM_PAI=PAIL AND TRIM(G.LISTA)=LISTAL )END  )
LEFT OUTER JOIN ORDEM5 H ON G.TIPO = 'PA' AND TRIM(H.LISTA) IN (SELECT CASE WHEN TRIM(LISTA)='REP' THEN 'M' ELSE TO_CHAR(TRIM(LISTA)) END  FROM LISTA_ATIVA_ULTIMA WHERE H.ITEM_PAI = TRIM(ITEM)) AND G.ITEM_FILHO = H.ITEM_PAI AND TRIM(G.FILIAL)=(CASE WHEN G.ITEM_FILHO LIKE 'RD%' AND G.FILIAL = '111000' THEN '111000' WHEN TRIM(G.FILIAL)='111005' THEN  '111005'  WHEN TRIM(G.FILIAL)='111002' THEN  '111002'  ELSE  TO_CHAR((REPLACE(TRIM(H.FILIAL),'111005','111000')))  END ) --AND TRIM(H.FILIAL) IN (CASE WHEN B.ITEM_FILHO LIKE 'RD%' THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE H.ITEM_PAI=PAIL AND TRIM(H.LISTA)=LISTAL )END  )


LEFT OUTER JOIN LISTA_ATIVA_ULTIMA D ON TRIM(A.LISTA) = TRIM(D.LISTA) AND TRIM(A.ITEM_PAI) = TRIM(D.ITEM)
LEFT OUTER JOIN DATA_PRODUCAO E ON TRIM(A.LISTA) = TRIM(E.LISTA) AND TRIM(A.ITEM_PAI) = TRIM(E.ITEM)
LEFT OUTER JOIN PRODDTA.F4101 F ON TRIM(A.ITEM_PAI) = TRIM(F.IMLITM)
LEFT OUTER JOIN PRODDTA.F4101 I ON TRIM(A.ITEM_FILHO) = TRIM(I.IMLITM)

where 
TRIM(nvl(B.FILIAL,'0')) = ( case when TRIM(B.FILIAL) IS NULL THEN '0' ELSE       (CASE WHEN B.ITEM_FILHO LIKE 'RD%' AND TRIM(I.IMSRP5)='MP'  THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE B.ITEM_PAI=PAIL AND TRIM(B.LISTA)=LISTAL )END  ) END)
AND TRIM(nvl(C.FILIAL,'0')) = ( case when TRIM(C.FILIAL) IS NULL THEN '0' ELSE   (CASE WHEN C.ITEM_FILHO LIKE 'RD%' AND TRIM(I.IMSRP5)='MP'  THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE C.ITEM_PAI=PAIL AND TRIM(C.LISTA)=LISTAL )END  ) END)
AND TRIM(nvl(G.FILIAL,'0')) = ( case when TRIM(G.FILIAL) IS NULL THEN '0' ELSE   (CASE WHEN G.ITEM_FILHO LIKE 'RD%' AND TRIM(I.IMSRP5)='MP'  THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE G.ITEM_PAI=PAIL AND TRIM(G.LISTA)=LISTAL )END  ) END)
AND TRIM(nvl(H.FILIAL,'0')) = ( case when TRIM(H.FILIAL) IS NULL THEN '0' ELSE   (CASE WHEN H.ITEM_FILHO LIKE 'RD%' AND TRIM(I.IMSRP5)='MP'  THEN '111002' ELSE (SELECT FILIALL FROM LISTA_FILIAL2 WHERE H.ITEM_PAI=PAIL AND TRIM(H.LISTA)=LISTAL )END  ) END)

--and  trim(A.ITEM_PAI)='148148'
-- where  D.LISTA IS NOT NULL

), custo2 as (
SELECT
SYSDATE DATA,
TO_CHAR(ITEM_PAI) ITEM,
 TO_CHAR(LISTA) LISTA,
ROUND(SUM(CUSTO_UNITARIO),6)  AS CUSTO_REAIS,
ROUND(ROUND(SUM(CUSTO_UNITARIO),6)/(select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),6) CUSTO_ESTRANGEIRO,
ROUND(CUSTO_SERV,6) CUSTO_SERV,
ROUND(CUSTO_MATE,6) CUSTO_MATE,
'BRL' AS MOEDA,
 (select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)) as CAMBIO,
CASE WHEN DATA_ULT_PRODUCAO IS NULL THEN 'N' ELSE 'S' END ULT_PRODUZIDA,
DATA_ULT_PRODUCAO,
TO_NUMBER(TO_CHAR(to_date(SYSDATE ), 'YYYYDDD'))-1900000 DATA_CUSTO,
CLASSE,
TRIM(DRDL01) DESCRICAO_CLASSE,
FILIAL,
          trim(imdsc1) as DSC,
       -- ROUND(SUM(CUSTO_UNITARIO),6)  / (select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)) CUSTO_UNITARIO,
    DESCRICAO_LISTA,
        ROUND((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='EUR' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),6) as BRL_EUR
,ROUND(SUM(CUSTO_UNITARIO),6)+ ROUND(CUSTO_SERV,6) AS CUSTO_TOTAL


FROM V_LISTA4
left join proddta.f4101 on trim(imlitm)=trim(ITEM_PAI)
LEFT JOIN PRODCTL.F0005  ON (IMSRP1)=TRIM(DRKY) and tRIM(DRSY)='41' AND TRIM(DRRT)='S1'
WHERE  FILIAL  in ('311000','111000','111005','111002','611000','311002','612000')
GROUP BY TO_CHAR(ITEM_PAI),trim(imdsc1),TO_CHAR(LISTA),ROUND(CUSTO_SERV,6),ROUND(CUSTO_MATE,6)  ,DESCRICAO_LISTA,FILIAL,CLASSE,TRIM(DRDL01),DATA_ULT_PRODUCAO
--ORDER BY DSC,LISTA
)
select SYSDATE DATA,to_char(ITEM) ITEM,TO_CHAR(LISTA) LISTA,to_number(CUSTO_REAIS) CUSTO_REAIS ,TO_NUMBER(CUSTO_ESTRANGEIRO) CUSTO_ESTRANGEIRO ,TO_NUMBER(CUSTO_SERV) CUSTO_SERV,TO_NUMBER(CUSTO_MATE) CUSTO_MATE,TO_CHAR(MOEDA) MOEDA,TO_NUMBER(CAMBIO) CAMBIO,to_char(ULT_PRODUZIDA) ULT_PRODUZIDA,to_char(DATA_ULT_PRODUCAO) DATA_ULT_PRODUCAO,to_number(DATA_CUSTO) DATA_CUSTO from custo2 WHERE  FILIAL  in ('111000')

UNION ALL
select SYSDATE DATA,to_char(ITEM) ITEM,TO_CHAR(LISTA) LISTA,to_number(CUSTO_REAIS) CUSTO_REAIS ,TO_NUMBER(CUSTO_ESTRANGEIRO) CUSTO_ESTRANGEIRO ,TO_NUMBER(CUSTO_SERV) CUSTO_SERV,TO_NUMBER(CUSTO_MATE) CUSTO_MATE,TO_CHAR(MOEDA) MOEDA,TO_NUMBER(CAMBIO) CAMBIO,to_char(ULT_PRODUZIDA) ULT_PRODUZIDA,to_char(DATA_ULT_PRODUCAO) DATA_ULT_PRODUCAO,to_number(DATA_CUSTO) DATA_CUSTO from custo2 A  WHERE  A.FILIAL  in ('311000') AND  not EXISTS (SELECT 1 FROM custo2 B WHERE A.ITEM=B.ITEM and A.LISTA=B.LISTA  AND B.FILIAL IN ('111000') )
UNION ALL
select SYSDATE DATA,to_char(ITEM) ITEM,TO_CHAR(LISTA) LISTA,to_number(CUSTO_REAIS) CUSTO_REAIS ,TO_NUMBER(CUSTO_ESTRANGEIRO) CUSTO_ESTRANGEIRO ,TO_NUMBER(CUSTO_SERV) CUSTO_SERV,TO_NUMBER(CUSTO_MATE) CUSTO_MATE,TO_CHAR(MOEDA) MOEDA,TO_NUMBER(CAMBIO) CAMBIO,to_char(ULT_PRODUZIDA) ULT_PRODUZIDA,to_char(DATA_ULT_PRODUCAO) DATA_ULT_PRODUCAO,to_number(DATA_CUSTO) DATA_CUSTO from custo2 A  WHERE  A.FILIAL  in ('111005','111002') AND  not EXISTS (SELECT 1 FROM custo2 B WHERE A.ITEM=B.ITEM and A.LISTA=B.LISTA  AND B.FILIAL IN ('311000','111000') )
UNION ALL
select SYSDATE DATA,to_char(ITEM) ITEM,TO_CHAR(LISTA) LISTA,to_number(CUSTO_REAIS) CUSTO_REAIS ,TO_NUMBER(CUSTO_ESTRANGEIRO) CUSTO_ESTRANGEIRO ,TO_NUMBER(CUSTO_SERV) CUSTO_SERV,TO_NUMBER(CUSTO_MATE) CUSTO_MATE,TO_CHAR(MOEDA) MOEDA,TO_NUMBER(CAMBIO) CAMBIO,to_char(ULT_PRODUZIDA) ULT_PRODUZIDA,to_char(DATA_ULT_PRODUCAO) DATA_ULT_PRODUCAO,to_number(DATA_CUSTO) DATA_CUSTO from custo2 A  WHERE  A.FILIAL  in ('611000') AND  not EXISTS (SELECT 1 FROM custo2 B WHERE A.ITEM=B.ITEM and A.LISTA=B.LISTA  AND B.FILIAL IN ('311000','111000','111005','111002') )
union all
select SYSDATE DATA,to_char(ITEM) ITEM,TO_CHAR(LISTA) LISTA,to_number(CUSTO_REAIS) CUSTO_REAIS ,TO_NUMBER(CUSTO_ESTRANGEIRO) CUSTO_ESTRANGEIRO ,TO_NUMBER(CUSTO_SERV) CUSTO_SERV,TO_NUMBER(CUSTO_MATE) CUSTO_MATE,TO_CHAR(MOEDA) MOEDA,TO_NUMBER(CAMBIO) CAMBIO,to_char(ULT_PRODUZIDA) ULT_PRODUZIDA,to_char(DATA_ULT_PRODUCAO) DATA_ULT_PRODUCAO,to_number(DATA_CUSTO) DATA_CUSTO from custo2 A  WHERE  A.FILIAL  in ('311002','612000') AND  not EXISTS (SELECT 1 FROM custo2 B WHERE A.ITEM=B.ITEM and A.LISTA=B.LISTA  AND B.FILIAL IN ('311000','111000','111005','111002','611000') )


union all


select
SYSDATE DATA,
to_char(trim(colitm)) as ITEM,
TO_CHAR('NET') LISTA,
CASE
WHEN COLEDG='41' THEN to_number(ROUND(COUNCS/10000*NVL((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),0),6))
WHEN COLEDG='42' THEN to_number(ROUND(COUNCS/10000*NVL((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='EUR' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),0),6) )
WHEN COLEDG='43' THEN to_number(ROUND(COUNCS/10000,6))
END CUSTO_REAIS,
CASE
WHEN COLEDG='41' THEN to_number(ROUND(COUNCS/10000,6))
WHEN COLEDG='42' THEN to_number(ROUND(COUNCS/10000*NVL((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),0)/(select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='EUR' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),6))
WHEN COLEDG='43' THEN to_number(ROUND(COUNCS/10000/(select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),6))
END CUSTO_ESTRANGEIRO,
0 CUSTO_SERV,
0 CUSTO_MATE,
TO_CHAR('BRL') MOEDA,
TO_NUMBER((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc))) CAMBIO,
'N' ULT_PRODUZIDA,
'' DATA_ULT_PRODUCAO,
TO_NUMBER(TO_CHAR(to_date(SYSDATE ), 'YYYYDDD'))-1900000 DATA_CUSTO
from proddta.f4101
inner join proddta.f4105 on imitm=coitm and TRIM(COMCU) = '111000'
left join proddta.f4102 on ibitm=coitm and TRIM(COMCU)=trim(ibmcu)
--LEFT JOIN proddta.F0015 a ON (CASE WHEN COLEDG='41' THEN 'USD' WHEN COLEDG='42' THEN 'EUR' WHEN COLEDG='43' THEN 'USD' END)=CXCRDC AND CXCRCD='BRL'   AND CXEFT= (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)
WHERE COLEDG IN ('41','42','43')
AND IMSRP5!='PA'



UNION ALL

select 

SYSDATE DATA,
to_char(TRIM(DRKY)) ITEM ,
TO_CHAR('EMB') LISTA,
TO_NUMBER(TRIM(DRDL02)) CUSTO_REAIS,
ROUND(TO_NUMBER(TRIM(DRDL02))/(select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc)),6) CUSTO_ESTRANGEIRO,
0 CUSTO_SERV,
0 CUSTO_MATE,
TO_CHAR('BRL') MOEDA,
TO_NUMBER((select trim(a.cxcrrd)  from proddta.F0015 a   where a.cxcrcd = 'BRL' and a.cxcrdc ='USD' and a.cxeft = (select max(b.cxeft) from proddta.F0015 b  where a.cxcrcd = b.cxcrcd and a.cxcrdc =b.cxcrdc))) CAMBIO,
'N' ULT_PRODUZIDA,
'' DATA_ULT_PRODUCAO,
TO_NUMBER(TO_CHAR(to_date(SYSDATE ), 'YYYYDDD'))-1900000 DATA_CUSTO
from PRODCTL.F0005 WHERE DRSY='55  '  AND DRRT='D4'
AND LENGTH(TRIM(TRANSLATE(DRDL02, '0123456789',' ')))='1'"