SELECT DISTINCT
    trim(A.CIMCU) AS CENTRO_CUSTO,
    trim(srp1.DRDL01) AS DESCRICAO_CLASSE,
    case when trim(srp1.DRDL01) = 'REVENDA' then TRIM(srp2.DRDL01)
    end AS DESCRICAO_SUBCLASSE,
    SUM (F.QTD) AS QTD,
    F.RECEITA_BRUTA_M_TOTAL,
    F.RECEITA_LIQUIDA_M_TOTAL,
    F.CUSTO_GERENCIAL_TOTAL,
    F.ICMS_TOTAL,
    F.CUSTO_EMBALAGEM_TOTAL,
    F.MES,
    F.ANO
FROM 
    proddta.F5549402 A
INNER JOIN 
    PRODCTL.F0005 srp1 
    ON srp1.DRSY = '41' 
    AND srp1.DRRT = 'S1' 
    AND TRIM(A.CISRP1) = TRIM(srp1.DRKY)
INNER JOIN 
    PRODCTL.F0005 srp2 
    ON srp2.DRSY = '41' 
    AND srp2.DRRT = 'S2' 
    AND TRIM(A.CISRP2) = TRIM(srp2.DRKY)
LEFT JOIN FaturamentoCusto F ON trim(A.CIMCU) = trim(F.CENTRO)
LEFT JOIN DESPESASCLASSE D ON trim(A.CIMCU)  = D.CENTRO
Group by trim(A.CIMCU),trim(srp1.DRDL01),srp2.DRDL01,F.QTD,
F.RECEITA_BRUTA_M_TOTAL,
    F.RECEITA_LIQUIDA_M_TOTAL,
    F.CUSTO_GERENCIAL_TOTAL,
    F.ICMS_TOTAL,
    F.CUSTO_EMBALAGEM_TOTAL,
    F.MES,F.ANO


SELECT DISTINCT
    trim(A.CIMCU) AS CENTRO_CUSTO,
    trim(srp1.DRDL01) AS DESCRICAO_CLASSE,
    case when trim(srp1.DRDL01) = 'REVENDA' then TRIM(srp2.DRDL01)
    end AS DESCRICAO_SUBCLASSE,
    SUM(D.VALOR_RECEBIDO)
FROM 
    proddta.F5549402 A
INNER JOIN 
    PRODCTL.F0005 srp1 
    ON srp1.DRSY = '41' 
    AND srp1.DRRT = 'S1' 
    AND TRIM(A.CISRP1) = TRIM(srp1.DRKY)
INNER JOIN 
    PRODCTL.F0005 srp2 
    ON srp2.DRSY = '41' 
    AND srp2.DRRT = 'S2' 
    AND TRIM(A.CISRP2) = TRIM(srp2.DRKY)
LEFT JOIN DESPESASCLASSE D ON trim(A.CIMCU)  = D.CENTRO