
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SILVER"."SL_CUSTO_GERENCIAL_V" ("DATA", "HORA", "FILIAL", "LISTA", "COD_ITEM", "MOEDA", "COTACAO_MOEDA", "CUSTO_UNITARIO", "CUSTO_DOLAR", "MAO_OBRA", "CUSTO_MAT_APLICADO", "CUSTO_TOTAL", "TIPO_LISTA", "CLASSE", "SUBCLASSE", "DESCRICAO1", "DESCRICAO2", "CAT_VENDA_COD5", "RN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT DISTINCT
    t.DATA,
    t.HORA,
    t.FILIAL,
    t.LISTA,
    t.COD_ITEM,
    t.MOEDA,
    t.COTACAO_MOEDA,
    t.CUSTO_UNITARIO,
    t.CUSTO_DOLAR,
    t.MAO_OBRA,
    t.CUSTO_MAT_APLICADO,
    t.CUSTO_TOTAL,
    t.TIPO_LISTA,
    srp1.DESCRICAO1 AS CLASSE,
    CASE WHEN TRIM(srp1.DESCRICAO1) = 'REVENDA' THEN to_char(TRIM(srp2.DESCRICAO1)) END AS SUBCLASSE,
    f4101_latest.DESCRICAO1,
    f4101_latest.DESCRICAO2,
    f4101_latest.CAT_VENDA_COD5,
    t.RN
FROM SILVER.SL_F5541054 t
INNER JOIN (
    SELECT *
    FROM (
        SELECT 
            SL_F4101.*,
            ROW_NUMBER() OVER (PARTITION BY COD_ITEM_SECUNDARIO ORDER BY DATA_atualizacao DESC) as rn
        FROM SILVER.SL_F4101
        WHERE CAT_VENDA_COD5 IN ('MP','PA', 'EM')
    ) 
    WHERE rn = 1
) f4101_latest ON t.COD_ITEM = f4101_latest.COD_ITEM_SECUNDARIO
LEFT JOIN SILVER.SL_F0005 srp1 
    ON srp1.SISTEMA = '41' 
    AND srp1.TIPO_REGISTRO = 'S1' 
    AND TRIM(f4101_latest.CLASSE_PRODUTO) = TRIM(srp1.CHAVE_REGISTRO)
LEFT JOIN SILVER.SL_F0005 srp2
    ON srp2.SISTEMA = '41'
    AND srp2.TIPO_REGISTRO = 'S2'
    AND TRIM(f4101_latest.SUBCLASSE_PRODUTO) = TRIM(srp2.CHAVE_REGISTRO)
WHERE t.TIPO_LISTA = 'M'
AND t.DATA > TO_DATE('01/01/2024', 'DD/MM/YYYY')
ORDER BY t.DATA ASC;

